// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

// Model - The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
type Model string

const (
	// ModelGemini25Flash Our first hybrid reasoning model which supports a 1M token context window and has thinking budgets.
	ModelGemini25Flash Model = "gemini-2.5-flash"
	// ModelGemini25Pro Our state-of-the-art multipurpose model, which excels at coding and complex reasoning tasks.
	ModelGemini25Pro Model = "gemini-2.5-pro"
	// ModelGemma426bA4bIt Gemma 4 26B A4B IT
	ModelGemma426bA4bIt Model = "gemma-4-26b-a4b-it"
	// ModelGemma431bIt Gemma 4 31B IT
	ModelGemma431bIt Model = "gemma-4-31b-it"
	// ModelGeminiFlashLatest Latest release of Gemini Flash
	ModelGeminiFlashLatest Model = "gemini-flash-latest"
	// ModelGeminiFlashLiteLatest Latest release of Gemini Flash-Lite
	ModelGeminiFlashLiteLatest Model = "gemini-flash-lite-latest"
	// ModelGeminiProLatest Latest release of Gemini Pro
	ModelGeminiProLatest Model = "gemini-pro-latest"
	// ModelGemini25FlashLite Our smallest and most cost effective model, built for at scale usage.
	ModelGemini25FlashLite Model = "gemini-2.5-flash-lite"
	// ModelGemini25FlashImage Our native image generation model, optimized for speed, flexibility, and contextual understanding. Text input and output is priced the same as 2.5 Flash.
	ModelGemini25FlashImage Model = "gemini-2.5-flash-image"
	// ModelGemini3FlashPreview Our most intelligent model built for speed, combining frontier intelligence with superior search and grounding.
	ModelGemini3FlashPreview Model = "gemini-3-flash-preview"
	// ModelGemini31ProPreview Our latest SOTA reasoning model with unprecedented depth and nuance, and powerful multimodal understanding and coding capabilities.
	ModelGemini31ProPreview Model = "gemini-3.1-pro-preview"
	// ModelGemini31ProPreviewCustomtools Gemini 3.1 Pro Preview optimized for custom tool usage
	ModelGemini31ProPreviewCustomtools Model = "gemini-3.1-pro-preview-customtools"
	// ModelGemini31FlashLite Our most cost-efficient model, optimized for high-volume agentic tasks, translation, and simple data processing.
	ModelGemini31FlashLite Model = "gemini-3.1-flash-lite"
	// ModelGemini3ProImage Gemini 3 Pro Image
	ModelGemini3ProImage Model = "gemini-3-pro-image"
	// ModelNanoBananaProPreview Gemini 3 Pro Image Preview
	ModelNanoBananaProPreview Model = "nano-banana-pro-preview"
	// ModelGemini31FlashImage Gemini 3.1 Flash Image.
	ModelGemini31FlashImage Model = "gemini-3.1-flash-image"
	// ModelGemini35Flash Gemini 3.5 Flash - Our earlier Flash model, built for speed and foundational performance across routine, high-throughput workloads.
	ModelGemini35Flash Model = "gemini-3.5-flash"
	// ModelGemini36Flash Gemini 3.6 Flash - Our previous generation Flash model, balancing speed and multimodal capabilities across general agentic and everyday tasks.
	ModelGemini36Flash Model = "gemini-3.6-flash"
	// ModelGemini37Flash Gemini 3.7 Flash - Our high-speed, efficient Flash model built for everyday coding, agentic tool use, and reliable multi-step execution.
	ModelGemini37Flash Model = "gemini-3.7-flash"
	// ModelGemini38Flash Gemini 3.8 Flash - Our most intelligent Flash model, engineered for long-horizon software engineering, autonomous agents, and complex enterprise workflows.
	ModelGemini38Flash Model = "gemini-3.8-flash"
	// ModelLyria3ClipPreview Our low-latency, music generation model optimized for high-fidelity audio clips and precise rhythmic control.
	ModelLyria3ClipPreview Model = "lyria-3-clip-preview"
	// ModelLyria3ProPreview Our advanced, full-song generative model with deep compositional understanding, optimized for precise structural control and complex transitions across diverse musical styles.
	ModelLyria3ProPreview Model = "lyria-3-pro-preview"
	// ModelGeminiRoboticsEr16Preview Gemini Robotics-ER 1.6 Preview
	ModelGeminiRoboticsEr16Preview Model = "gemini-robotics-er-1.6-preview"
	// ModelGeminiRoboticsEr2Preview Gemini Robotics Embodied Reasoning 2 Preview
	ModelGeminiRoboticsEr2Preview Model = "gemini-robotics-er-2-preview"
)

func (e Model) ToPointer() *Model {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Model) IsExact() bool {
	if e != nil {
		switch *e {
		case "gemini-2.5-flash", "gemini-2.5-pro", "gemma-4-26b-a4b-it", "gemma-4-31b-it", "gemini-flash-latest", "gemini-flash-lite-latest", "gemini-pro-latest", "gemini-2.5-flash-lite", "gemini-2.5-flash-image", "gemini-3-flash-preview", "gemini-3.1-pro-preview", "gemini-3.1-pro-preview-customtools", "gemini-3.1-flash-lite", "gemini-3-pro-image", "nano-banana-pro-preview", "gemini-3.1-flash-image", "gemini-3.5-flash", "gemini-3.6-flash", "gemini-3.7-flash", "gemini-3.8-flash", "lyria-3-clip-preview", "lyria-3-pro-preview", "gemini-robotics-er-1.6-preview", "gemini-robotics-er-2-preview":
			return true
		}
	}
	return false
}
