// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agents

import (
	"encoding/json"
	"errors"

	"google.golang.org/genai/gaos/internal/utils"
	"google.golang.org/genai/gaos/models/interactions"
)

type BaseEnvironmentType string

const (
	BaseEnvironmentTypeEnvironment BaseEnvironmentType = "Environment"
	BaseEnvironmentTypeStr         BaseEnvironmentType = "str"
	BaseEnvironmentTypeUnknown     BaseEnvironmentType = "Unknown"
)

// BaseEnvironment - The environment configuration for the agent.
type BaseEnvironment struct {
	Environment *interactions.Environment `queryParam:"inline" union:"member"`
	Str         *string                   `queryParam:"inline" union:"member"`
	UnknownRaw  json.RawMessage           `json:"-" union:"unknown"`

	Type BaseEnvironmentType
}

func CreateBaseEnvironmentEnvironment(environment interactions.Environment) BaseEnvironment {
	typ := BaseEnvironmentTypeEnvironment

	return BaseEnvironment{
		Environment: &environment,
		Type:        typ,
	}
}

func CreateBaseEnvironmentStr(str string) BaseEnvironment {
	typ := BaseEnvironmentTypeStr

	return BaseEnvironment{
		Str:  &str,
		Type: typ,
	}
}

func CreateBaseEnvironmentUnknown(raw json.RawMessage) BaseEnvironment {
	return BaseEnvironment{
		UnknownRaw: raw,
		Type:       BaseEnvironmentTypeUnknown,
	}
}

func (u BaseEnvironment) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u BaseEnvironment) IsUnknown() bool {
	return u.Type == BaseEnvironmentTypeUnknown
}

func (u *BaseEnvironment) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var environment interactions.Environment = interactions.Environment{}
	if err := utils.UnmarshalJSON(data, &environment, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  BaseEnvironmentTypeEnvironment,
			Value: &environment,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  BaseEnvironmentTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = BaseEnvironmentTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = BaseEnvironmentTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(BaseEnvironmentType)
	switch best.Type {
	case BaseEnvironmentTypeEnvironment:
		u.Environment = best.Value.(*interactions.Environment)
		return nil
	case BaseEnvironmentTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = BaseEnvironmentTypeUnknown
	return nil
}

func (u BaseEnvironment) MarshalJSON() ([]byte, error) {
	if u.Environment != nil {
		return utils.MarshalJSON(u.Environment, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type BaseEnvironment: all fields are null")
}

// Agent - An agent definition for the CreateAgent API.
// This message is the target for annotation-parser-based JSON parsing.
// New format:
//
//	{
//	  "id": "customer-sentinel",
//	  "base_agent": "",
//	  "system_instruction": "...",
//	  "base_environment": { "type": "remote", "sources": [...] },
//	  "tools": [ {"type": "code_execution"} ]
//	}
type Agent struct {
	// The base agent to extend.
	BaseAgent *string `json:"base_agent,omitzero"`
	// The environment configuration for the agent.
	BaseEnvironment *BaseEnvironment `json:"base_environment,omitzero"`
	// Agent description for developers to quickly read and understand.
	Description *string `json:"description,omitzero"`
	// The unique identifier for the agent.
	ID *string `json:"id,omitzero"`
	// System instruction for the agent.
	SystemInstruction *string `json:"system_instruction,omitzero"`
	// The tools available to the agent.
	Tools []AgentTool `json:"tools,omitzero"`
}

func (a Agent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Agent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Agent) GetBaseAgent() *string {
	if a == nil {
		return nil
	}
	return a.BaseAgent
}

func (a *Agent) GetBaseEnvironment() *BaseEnvironment {
	if a == nil {
		return nil
	}
	return a.BaseEnvironment
}

func (a *Agent) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *Agent) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *Agent) GetSystemInstruction() *string {
	if a == nil {
		return nil
	}
	return a.SystemInstruction
}

func (a *Agent) GetTools() []AgentTool {
	if a == nil {
		return nil
	}
	return a.Tools
}
