// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"google.golang.org/genai/gaos/internal/utils"
	"google.golang.org/genai/gaos/models/components"
	"google.golang.org/genai/gaos/models/interactions"
)

type CancelInteractionByIDGlobals struct {
	// Which version of the API to use.
	APIVersion *string `pathParam:"style=simple,explode=false,name=api_version"`
}

func (c *CancelInteractionByIDGlobals) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

type CancelInteractionByIDRequest struct {
	// The unique identifier of the interaction to cancel.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Which version of the API to use.
	APIVersion *string `pathParam:"style=simple,explode=false,name=api_version"`
}

func (c *CancelInteractionByIDRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CancelInteractionByIDRequest) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

type CancelInteractionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful cancellation of the interaction.
	Interaction *interactions.Interaction
}

func (c CancelInteractionByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelInteractionByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelInteractionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelInteractionByIDResponse) GetInteraction() *interactions.Interaction {
	if c == nil {
		return nil
	}
	return c.Interaction
}
