// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
	"google.golang.org/genai/gaos/models/components"
	"google.golang.org/genai/gaos/models/interactions"
	"google.golang.org/genai/gaos/types/stream"
)

type CreateInteractionGlobals struct {
	// Which version of the API to use.
	APIVersion *string `pathParam:"style=simple,explode=false,name=api_version"`
}

func (c *CreateInteractionGlobals) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

type CreateInteractionRequestBodyType string

const (
	CreateInteractionRequestBodyTypeCreateModelInteraction CreateInteractionRequestBodyType = "CreateModelInteraction"
	CreateInteractionRequestBodyTypeCreateAgentInteraction CreateInteractionRequestBodyType = "CreateAgentInteraction"
)

// CreateInteractionRequestBody - The request body.
type CreateInteractionRequestBody struct {
	CreateModelInteraction *interactions.CreateModelInteraction `queryParam:"inline" union:"member"`
	CreateAgentInteraction *interactions.CreateAgentInteraction `queryParam:"inline" union:"member"`

	Type CreateInteractionRequestBodyType
}

func CreateCreateInteractionRequestBodyCreateModelInteraction(createModelInteraction interactions.CreateModelInteraction) CreateInteractionRequestBody {
	typ := CreateInteractionRequestBodyTypeCreateModelInteraction

	return CreateInteractionRequestBody{
		CreateModelInteraction: &createModelInteraction,
		Type:                   typ,
	}
}

func CreateCreateInteractionRequestBodyCreateAgentInteraction(createAgentInteraction interactions.CreateAgentInteraction) CreateInteractionRequestBody {
	typ := CreateInteractionRequestBodyTypeCreateAgentInteraction

	return CreateInteractionRequestBody{
		CreateAgentInteraction: &createAgentInteraction,
		Type:                   typ,
	}
}

func (u *CreateInteractionRequestBody) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var createModelInteraction interactions.CreateModelInteraction = interactions.CreateModelInteraction{}
	if err := utils.UnmarshalJSON(data, &createModelInteraction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateInteractionRequestBodyTypeCreateModelInteraction,
			Value: &createModelInteraction,
		})
	}

	var createAgentInteraction interactions.CreateAgentInteraction = interactions.CreateAgentInteraction{}
	if err := utils.UnmarshalJSON(data, &createAgentInteraction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateInteractionRequestBodyTypeCreateAgentInteraction,
			Value: &createAgentInteraction,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateInteractionRequestBody", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateInteractionRequestBody", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreateInteractionRequestBodyType)
	switch best.Type {
	case CreateInteractionRequestBodyTypeCreateModelInteraction:
		u.CreateModelInteraction = best.Value.(*interactions.CreateModelInteraction)
		return nil
	case CreateInteractionRequestBodyTypeCreateAgentInteraction:
		u.CreateAgentInteraction = best.Value.(*interactions.CreateAgentInteraction)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateInteractionRequestBody", string(data))
}

func (u CreateInteractionRequestBody) MarshalJSON() ([]byte, error) {
	if u.CreateModelInteraction != nil {
		return utils.MarshalJSON(u.CreateModelInteraction, "", true)
	}

	if u.CreateAgentInteraction != nil {
		return utils.MarshalJSON(u.CreateAgentInteraction, "", true)
	}

	return nil, errors.New("could not marshal union type CreateInteractionRequestBody: all fields are null")
}

type CreateInteractionRequest struct {
	// Which version of the API to use.
	APIVersion *string `pathParam:"style=simple,explode=false,name=api_version"`
	// The request body.
	Body CreateInteractionRequestBody `request:"mediaType=application/json"`
}

func (c *CreateInteractionRequest) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

func (c *CreateInteractionRequest) GetBody() CreateInteractionRequestBody {
	if c == nil {
		return CreateInteractionRequestBody{}
	}
	return c.Body
}

type CreateInteractionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Interaction *interactions.Interaction
	// Successful operation
	InteractionSSEStreamEvent *stream.EventStream[interactions.InteractionSSEStreamEvent]
}

func (c CreateInteractionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInteractionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInteractionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateInteractionResponse) GetInteraction() *interactions.Interaction {
	if c == nil {
		return nil
	}
	return c.Interaction
}

func (c *CreateInteractionResponse) GetInteractionSSEStreamEvent() *stream.EventStream[interactions.InteractionSSEStreamEvent] {
	if c == nil {
		return nil
	}
	return c.InteractionSSEStreamEvent
}
