// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"google.golang.org/genai/gaos/internal/utils"
	"google.golang.org/genai/gaos/models/components"
	"google.golang.org/genai/gaos/models/environments"
)

type GetEnvironmentFilesGlobals struct {
	// Which version of the API to use.
	APIVersion *string `pathParam:"style=simple,explode=false,name=api_version"`
}

func (g *GetEnvironmentFilesGlobals) GetAPIVersion() *string {
	if g == nil {
		return nil
	}
	return g.APIVersion
}

type GetEnvironmentFilesRequest struct {
	// Which version of the API to use.
	APIVersion  *string `pathParam:"style=simple,explode=false,name=api_version"`
	Environment string  `pathParam:"style=simple,explode=false,name=environment"`
	Path        string  `pathParam:"style=simple,explode=false,name=path"`
	// Optional. Maximum number of entries to return per page (for directory listing).
	PageSize *int `queryParam:"style=form,explode=true,name=page_size"`
	// Optional. Pagination token for directory listing.
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Optional. If true and the path is a directory, recursively lists all files.
	Recursive *bool `queryParam:"style=form,explode=true,name=recursive"`
}

func (g *GetEnvironmentFilesRequest) GetAPIVersion() *string {
	if g == nil {
		return nil
	}
	return g.APIVersion
}

func (g *GetEnvironmentFilesRequest) GetEnvironment() string {
	if g == nil {
		return ""
	}
	return g.Environment
}

func (g *GetEnvironmentFilesRequest) GetPath() string {
	if g == nil {
		return ""
	}
	return g.Path
}

func (g *GetEnvironmentFilesRequest) GetPageSize() *int {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetEnvironmentFilesRequest) GetPageToken() *string {
	if g == nil {
		return nil
	}
	return g.PageToken
}

func (g *GetEnvironmentFilesRequest) GetRecursive() *bool {
	if g == nil {
		return nil
	}
	return g.Recursive
}

type GetEnvironmentFilesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	GetEnvironmentFilesResponse *environments.GetEnvironmentFilesResponse
}

func (g GetEnvironmentFilesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEnvironmentFilesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEnvironmentFilesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEnvironmentFilesResponse) GetGetEnvironmentFilesResponse() *environments.GetEnvironmentFilesResponse {
	if g == nil {
		return nil
	}
	return g.GetEnvironmentFilesResponse
}
