// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package triggers

import (
	"errors"
	"fmt"

	"google.golang.org/genai/gaos/internal/utils"
	"google.golang.org/genai/gaos/models/interactions"
)

type InteractionType string

const (
	InteractionTypeCreateAgentInteraction InteractionType = "CreateAgentInteraction"
	InteractionTypeCreateModelInteraction InteractionType = "CreateModelInteraction"
)

// Interaction - Required. The interaction request template to be executed.
type Interaction struct {
	CreateAgentInteraction *interactions.CreateAgentInteraction `queryParam:"inline" union:"member"`
	CreateModelInteraction *interactions.CreateModelInteraction `queryParam:"inline" union:"member"`

	Type InteractionType
}

func CreateInteractionCreateAgentInteraction(createAgentInteraction interactions.CreateAgentInteraction) Interaction {
	typ := InteractionTypeCreateAgentInteraction

	return Interaction{
		CreateAgentInteraction: &createAgentInteraction,
		Type:                   typ,
	}
}

func CreateInteractionCreateModelInteraction(createModelInteraction interactions.CreateModelInteraction) Interaction {
	typ := InteractionTypeCreateModelInteraction

	return Interaction{
		CreateModelInteraction: &createModelInteraction,
		Type:                   typ,
	}
}

func (u *Interaction) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var createAgentInteraction interactions.CreateAgentInteraction = interactions.CreateAgentInteraction{}
	if err := utils.UnmarshalJSON(data, &createAgentInteraction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionTypeCreateAgentInteraction,
			Value: &createAgentInteraction,
		})
	}

	var createModelInteraction interactions.CreateModelInteraction = interactions.CreateModelInteraction{}
	if err := utils.UnmarshalJSON(data, &createModelInteraction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionTypeCreateModelInteraction,
			Value: &createModelInteraction,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Interaction", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Interaction", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InteractionType)
	switch best.Type {
	case InteractionTypeCreateAgentInteraction:
		u.CreateAgentInteraction = best.Value.(*interactions.CreateAgentInteraction)
		return nil
	case InteractionTypeCreateModelInteraction:
		u.CreateModelInteraction = best.Value.(*interactions.CreateModelInteraction)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Interaction", string(data))
}

func (u Interaction) MarshalJSON() ([]byte, error) {
	if u.CreateAgentInteraction != nil {
		return utils.MarshalJSON(u.CreateAgentInteraction, "", true)
	}

	if u.CreateModelInteraction != nil {
		return utils.MarshalJSON(u.CreateModelInteraction, "", true)
	}

	return nil, errors.New("could not marshal union type Interaction: all fields are null")
}

// TriggerCreateParams - Parameters for creating a trigger.
type TriggerCreateParams struct {
	// Required. The cron schedule on which the trigger should run. Standard cron format.
	Schedule string `json:"schedule"`
	// Required. Time zone in which the schedule should be interpreted.
	TimeZone string `json:"time_zone"`
	// Optional. The display name of the trigger.
	DisplayName *string `json:"display_name,omitzero"`
	// Optional. The environment ID for the trigger execution.
	EnvironmentID *string `json:"environment_id,omitzero"`
	// Optional. The maximum number of consecutive failures allowed before the trigger is automatically paused (status becomes ERROR).
	MaxConsecutiveFailures *int `json:"max_consecutive_failures,omitzero"`
	// Optional. The execution timeout for the triggered interaction.
	ExecutionTimeoutSeconds *int `json:"execution_timeout_seconds,omitzero"`
	// Required. The interaction request template to be executed.
	Interaction Interaction `json:"interaction"`
}

func (t *TriggerCreateParams) GetSchedule() string {
	if t == nil {
		return ""
	}
	return t.Schedule
}

func (t *TriggerCreateParams) GetTimeZone() string {
	if t == nil {
		return ""
	}
	return t.TimeZone
}

func (t *TriggerCreateParams) GetDisplayName() *string {
	if t == nil {
		return nil
	}
	return t.DisplayName
}

func (t *TriggerCreateParams) GetEnvironmentID() *string {
	if t == nil {
		return nil
	}
	return t.EnvironmentID
}

func (t *TriggerCreateParams) GetMaxConsecutiveFailures() *int {
	if t == nil {
		return nil
	}
	return t.MaxConsecutiveFailures
}

func (t *TriggerCreateParams) GetExecutionTimeoutSeconds() *int {
	if t == nil {
		return nil
	}
	return t.ExecutionTimeoutSeconds
}

func (t *TriggerCreateParams) GetInteraction() Interaction {
	if t == nil {
		return Interaction{}
	}
	return t.Interaction
}
