// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"google.golang.org/genai/gaos/internal/utils"
)

// AllowlistEntry - A single domain allowlist rule with optional header injection.
type AllowlistEntry struct {
	// Domain to allow outbound requests to. Supports wildcards (e.g. '*.googleapis.com'). Use '*' to allow all domains.
	Domain string `json:"domain"`
	// Headers to inject on all outbound requests matching this domain. Each entry is a flat {header_name: header_value} object. The egress proxy injects these automatically.
	Transform []map[string]string `json:"transform,omitzero"`
}

func (a AllowlistEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AllowlistEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AllowlistEntry) GetDomain() string {
	if a == nil {
		return ""
	}
	return a.Domain
}

func (a *AllowlistEntry) GetTransform() []map[string]string {
	if a == nil {
		return nil
	}
	return a.Transform
}
