// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type AnnotationType string

const (
	AnnotationTypeURLCitation   AnnotationType = "url_citation"
	AnnotationTypeFileCitation  AnnotationType = "file_citation"
	AnnotationTypePlaceCitation AnnotationType = "place_citation"
	AnnotationTypeUnknown       AnnotationType = "UNKNOWN"
)

// Annotation - Citation information for model-generated content.
type Annotation struct {
	URLCitation   *URLCitation    `queryParam:"inline" union:"member"`
	FileCitation  *FileCitation   `queryParam:"inline" union:"member"`
	PlaceCitation *PlaceCitation  `queryParam:"inline" union:"member"`
	UnknownRaw    json.RawMessage `json:"-" union:"unknown"`

	Type AnnotationType
}

func CreateAnnotationURLCitation(urlCitation URLCitation) Annotation {
	typ := AnnotationTypeURLCitation

	return Annotation{
		URLCitation: &urlCitation,
		Type:        typ,
	}
}

func CreateAnnotationFileCitation(fileCitation FileCitation) Annotation {
	typ := AnnotationTypeFileCitation

	return Annotation{
		FileCitation: &fileCitation,
		Type:         typ,
	}
}

func CreateAnnotationPlaceCitation(placeCitation PlaceCitation) Annotation {
	typ := AnnotationTypePlaceCitation

	return Annotation{
		PlaceCitation: &placeCitation,
		Type:          typ,
	}
}

func CreateAnnotationUnknown(raw json.RawMessage) Annotation {
	return Annotation{
		UnknownRaw: raw,
		Type:       AnnotationTypeUnknown,
	}
}

func (u Annotation) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Annotation) IsUnknown() bool {
	return u.Type == AnnotationTypeUnknown
}

func (u *Annotation) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnnotationTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnnotationTypeUnknown
		return nil
	}

	switch dis.Type {
	case "url_citation":
		urlCitation := new(URLCitation)
		if err := utils.UnmarshalJSON(data, &urlCitation, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == url_citation) type URLCitation within Annotation: %w", string(data), err)
		}

		u.URLCitation = urlCitation
		u.Type = AnnotationTypeURLCitation
		return nil
	case "file_citation":
		fileCitation := new(FileCitation)
		if err := utils.UnmarshalJSON(data, &fileCitation, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_citation) type FileCitation within Annotation: %w", string(data), err)
		}

		u.FileCitation = fileCitation
		u.Type = AnnotationTypeFileCitation
		return nil
	case "place_citation":
		placeCitation := new(PlaceCitation)
		if err := utils.UnmarshalJSON(data, &placeCitation, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == place_citation) type PlaceCitation within Annotation: %w", string(data), err)
		}

		u.PlaceCitation = placeCitation
		u.Type = AnnotationTypePlaceCitation
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnnotationTypeUnknown
		return nil
	}

}

func (u Annotation) MarshalJSON() ([]byte, error) {
	if u.URLCitation != nil {
		return utils.MarshalJSON(u.URLCitation, "", true)
	}

	if u.FileCitation != nil {
		return utils.MarshalJSON(u.FileCitation, "", true)
	}

	if u.PlaceCitation != nil {
		return utils.MarshalJSON(u.PlaceCitation, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Annotation: all fields are null")
}
