// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type ContentType string

const (
	ContentTypeText     ContentType = "text"
	ContentTypeImage    ContentType = "image"
	ContentTypeAudio    ContentType = "audio"
	ContentTypeDocument ContentType = "document"
	ContentTypeVideo    ContentType = "video"
	ContentTypeUnknown  ContentType = "UNKNOWN"
)

// Content - The content of the response.
type Content struct {
	TextContent     *TextContent     `queryParam:"inline" union:"member"`
	ImageContent    *ImageContent    `queryParam:"inline" union:"member"`
	AudioContent    *AudioContent    `queryParam:"inline" union:"member"`
	DocumentContent *DocumentContent `queryParam:"inline" union:"member"`
	VideoContent    *VideoContent    `queryParam:"inline" union:"member"`
	UnknownRaw      json.RawMessage  `json:"-" union:"unknown"`

	Type ContentType
}

func CreateContentText(text TextContent) Content {
	typ := ContentTypeText

	return Content{
		TextContent: &text,
		Type:        typ,
	}
}

func CreateContentImage(image ImageContent) Content {
	typ := ContentTypeImage

	return Content{
		ImageContent: &image,
		Type:         typ,
	}
}

func CreateContentAudio(audio AudioContent) Content {
	typ := ContentTypeAudio

	return Content{
		AudioContent: &audio,
		Type:         typ,
	}
}

func CreateContentDocument(document DocumentContent) Content {
	typ := ContentTypeDocument

	return Content{
		DocumentContent: &document,
		Type:            typ,
	}
}

func CreateContentVideo(video VideoContent) Content {
	typ := ContentTypeVideo

	return Content{
		VideoContent: &video,
		Type:         typ,
	}
}

func CreateContentUnknown(raw json.RawMessage) Content {
	return Content{
		UnknownRaw: raw,
		Type:       ContentTypeUnknown,
	}
}

func (u Content) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Content) IsUnknown() bool {
	return u.Type == ContentTypeUnknown
}

func (u *Content) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ContentTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ContentTypeUnknown
		return nil
	}

	switch dis.Type {
	case "text":
		textContent := new(TextContent)
		if err := utils.UnmarshalJSON(data, &textContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type TextContent within Content: %w", string(data), err)
		}

		u.TextContent = textContent
		u.Type = ContentTypeText
		return nil
	case "image":
		imageContent := new(ImageContent)
		if err := utils.UnmarshalJSON(data, &imageContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image) type ImageContent within Content: %w", string(data), err)
		}

		u.ImageContent = imageContent
		u.Type = ContentTypeImage
		return nil
	case "audio":
		audioContent := new(AudioContent)
		if err := utils.UnmarshalJSON(data, &audioContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == audio) type AudioContent within Content: %w", string(data), err)
		}

		u.AudioContent = audioContent
		u.Type = ContentTypeAudio
		return nil
	case "document":
		documentContent := new(DocumentContent)
		if err := utils.UnmarshalJSON(data, &documentContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == document) type DocumentContent within Content: %w", string(data), err)
		}

		u.DocumentContent = documentContent
		u.Type = ContentTypeDocument
		return nil
	case "video":
		videoContent := new(VideoContent)
		if err := utils.UnmarshalJSON(data, &videoContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == video) type VideoContent within Content: %w", string(data), err)
		}

		u.VideoContent = videoContent
		u.Type = ContentTypeVideo
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ContentTypeUnknown
		return nil
	}

}

func (u Content) MarshalJSON() ([]byte, error) {
	if u.TextContent != nil {
		return utils.MarshalJSON(u.TextContent, "", true)
	}

	if u.ImageContent != nil {
		return utils.MarshalJSON(u.ImageContent, "", true)
	}

	if u.AudioContent != nil {
		return utils.MarshalJSON(u.AudioContent, "", true)
	}

	if u.DocumentContent != nil {
		return utils.MarshalJSON(u.DocumentContent, "", true)
	}

	if u.VideoContent != nil {
		return utils.MarshalJSON(u.VideoContent, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Content: all fields are null")
}
