// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type CreateAgentInteractionResponseFormatType string

const (
	CreateAgentInteractionResponseFormatTypeArrayOfResponseFormat CreateAgentInteractionResponseFormatType = "arrayOfResponseFormat"
	CreateAgentInteractionResponseFormatTypeResponseFormat        CreateAgentInteractionResponseFormatType = "ResponseFormat"
)

// CreateAgentInteractionResponseFormat - Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
type CreateAgentInteractionResponseFormat struct {
	ArrayOfResponseFormat []ResponseFormat `queryParam:"inline" union:"member"`
	ResponseFormat        *ResponseFormat  `queryParam:"inline" union:"member"`

	Type CreateAgentInteractionResponseFormatType
}

func CreateCreateAgentInteractionResponseFormatArrayOfResponseFormat(arrayOfResponseFormat []ResponseFormat) CreateAgentInteractionResponseFormat {
	typ := CreateAgentInteractionResponseFormatTypeArrayOfResponseFormat

	return CreateAgentInteractionResponseFormat{
		ArrayOfResponseFormat: arrayOfResponseFormat,
		Type:                  typ,
	}
}

func CreateCreateAgentInteractionResponseFormatResponseFormat(responseFormat ResponseFormat) CreateAgentInteractionResponseFormat {
	typ := CreateAgentInteractionResponseFormatTypeResponseFormat

	return CreateAgentInteractionResponseFormat{
		ResponseFormat: &responseFormat,
		Type:           typ,
	}
}

func (u *CreateAgentInteractionResponseFormat) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfResponseFormat []ResponseFormat = []ResponseFormat{}
	if err := utils.UnmarshalJSON(data, &arrayOfResponseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateAgentInteractionResponseFormatTypeArrayOfResponseFormat,
			Value: arrayOfResponseFormat,
		})
	}

	var responseFormat ResponseFormat = ResponseFormat{}
	if err := utils.UnmarshalJSON(data, &responseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateAgentInteractionResponseFormatTypeResponseFormat,
			Value: &responseFormat,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionResponseFormat", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionResponseFormat", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreateAgentInteractionResponseFormatType)
	switch best.Type {
	case CreateAgentInteractionResponseFormatTypeArrayOfResponseFormat:
		u.ArrayOfResponseFormat = best.Value.([]ResponseFormat)
		return nil
	case CreateAgentInteractionResponseFormatTypeResponseFormat:
		u.ResponseFormat = best.Value.(*ResponseFormat)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionResponseFormat", string(data))
}

func (u CreateAgentInteractionResponseFormat) MarshalJSON() ([]byte, error) {
	if u.ArrayOfResponseFormat != nil {
		return utils.MarshalJSON(u.ArrayOfResponseFormat, "", true)
	}

	if u.ResponseFormat != nil {
		return utils.MarshalJSON(u.ResponseFormat, "", true)
	}

	return nil, errors.New("could not marshal union type CreateAgentInteractionResponseFormat: all fields are null")
}

type CreateAgentInteractionEnvironmentType string

const (
	CreateAgentInteractionEnvironmentTypeStr         CreateAgentInteractionEnvironmentType = "str"
	CreateAgentInteractionEnvironmentTypeEnvironment CreateAgentInteractionEnvironmentType = "Environment"
)

// CreateAgentInteractionEnvironment - The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
type CreateAgentInteractionEnvironment struct {
	Str         *string      `queryParam:"inline" union:"member"`
	Environment *Environment `queryParam:"inline" union:"member"`

	Type CreateAgentInteractionEnvironmentType
}

func CreateCreateAgentInteractionEnvironmentStr(str string) CreateAgentInteractionEnvironment {
	typ := CreateAgentInteractionEnvironmentTypeStr

	return CreateAgentInteractionEnvironment{
		Str:  &str,
		Type: typ,
	}
}

func CreateCreateAgentInteractionEnvironmentEnvironment(environment Environment) CreateAgentInteractionEnvironment {
	typ := CreateAgentInteractionEnvironmentTypeEnvironment

	return CreateAgentInteractionEnvironment{
		Environment: &environment,
		Type:        typ,
	}
}

func (u *CreateAgentInteractionEnvironment) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateAgentInteractionEnvironmentTypeStr,
			Value: &str,
		})
	}

	var environment Environment = Environment{}
	if err := utils.UnmarshalJSON(data, &environment, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateAgentInteractionEnvironmentTypeEnvironment,
			Value: &environment,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionEnvironment", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionEnvironment", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreateAgentInteractionEnvironmentType)
	switch best.Type {
	case CreateAgentInteractionEnvironmentTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case CreateAgentInteractionEnvironmentTypeEnvironment:
		u.Environment = best.Value.(*Environment)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionEnvironment", string(data))
}

func (u CreateAgentInteractionEnvironment) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Environment != nil {
		return utils.MarshalJSON(u.Environment, "", true)
	}

	return nil, errors.New("could not marshal union type CreateAgentInteractionEnvironment: all fields are null")
}

type CreateAgentInteractionAgentConfigType string

const (
	CreateAgentInteractionAgentConfigTypeDynamic      CreateAgentInteractionAgentConfigType = "dynamic"
	CreateAgentInteractionAgentConfigTypeDeepResearch CreateAgentInteractionAgentConfigType = "deep-research"
)

// CreateAgentInteractionAgentConfig - Configuration parameters for the agent interaction.
type CreateAgentInteractionAgentConfig struct {
	DynamicAgentConfig      *DynamicAgentConfig      `queryParam:"inline" union:"member"`
	DeepResearchAgentConfig *DeepResearchAgentConfig `queryParam:"inline" union:"member"`

	Type CreateAgentInteractionAgentConfigType
}

func CreateCreateAgentInteractionAgentConfigDynamic(dynamic DynamicAgentConfig) CreateAgentInteractionAgentConfig {
	typ := CreateAgentInteractionAgentConfigTypeDynamic

	return CreateAgentInteractionAgentConfig{
		DynamicAgentConfig: &dynamic,
		Type:               typ,
	}
}

func CreateCreateAgentInteractionAgentConfigDeepResearch(deepResearch DeepResearchAgentConfig) CreateAgentInteractionAgentConfig {
	typ := CreateAgentInteractionAgentConfigTypeDeepResearch

	return CreateAgentInteractionAgentConfig{
		DeepResearchAgentConfig: &deepResearch,
		Type:                    typ,
	}
}

func (u *CreateAgentInteractionAgentConfig) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "dynamic":
		dynamicAgentConfig := new(DynamicAgentConfig)
		if err := utils.UnmarshalJSON(data, &dynamicAgentConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == dynamic) type DynamicAgentConfig within CreateAgentInteractionAgentConfig: %w", string(data), err)
		}

		u.DynamicAgentConfig = dynamicAgentConfig
		u.Type = CreateAgentInteractionAgentConfigTypeDynamic
		return nil
	case "deep-research":
		deepResearchAgentConfig := new(DeepResearchAgentConfig)
		if err := utils.UnmarshalJSON(data, &deepResearchAgentConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == deep-research) type DeepResearchAgentConfig within CreateAgentInteractionAgentConfig: %w", string(data), err)
		}

		u.DeepResearchAgentConfig = deepResearchAgentConfig
		u.Type = CreateAgentInteractionAgentConfigTypeDeepResearch
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAgentInteractionAgentConfig", string(data))
}

func (u CreateAgentInteractionAgentConfig) MarshalJSON() ([]byte, error) {
	if u.DynamicAgentConfig != nil {
		return utils.MarshalJSON(u.DynamicAgentConfig, "", true)
	}

	if u.DeepResearchAgentConfig != nil {
		return utils.MarshalJSON(u.DeepResearchAgentConfig, "", true)
	}

	return nil, errors.New("could not marshal union type CreateAgentInteractionAgentConfig: all fields are null")
}

// CreateAgentInteraction - Parameters for creating agent interactions
type CreateAgentInteraction struct {
	// The agent to interact with.
	Agent AgentOption `json:"agent"`
	// Input only. Whether the interaction will be streamed.
	Stream *bool `json:"stream,omitzero"`
	// Input only. Whether to store the response and request for later retrieval.
	Store *bool `json:"store,omitzero"`
	// Input only. Whether to run the model interaction in the background.
	Background *bool `json:"background,omitzero"`
	// System instruction for the interaction.
	SystemInstruction *string `json:"system_instruction,omitzero"`
	// A list of tool declarations the model may call during interaction.
	Tools []Tool `json:"tools,omitzero"`
	// The requested modalities of the response (TEXT, IMAGE, AUDIO).
	ResponseModalities []ResponseModality `json:"response_modalities,omitzero"`
	// The mime type of the response. This is required if response_format is set.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ResponseMimeType *string `json:"response_mime_type,omitzero"`
	// The ID of the previous interaction, if any.
	PreviousInteractionID *string      `json:"previous_interaction_id,omitzero"`
	ServiceTier           *ServiceTier `json:"service_tier,omitzero"`
	// Message for configuring webhook events for a request.
	WebhookConfig *WebhookConfig `json:"webhook_config,omitzero"`
	// Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
	ResponseFormat *CreateAgentInteractionResponseFormat `json:"response_format,omitzero"`
	// The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
	Environment *CreateAgentInteractionEnvironment `json:"environment,omitzero"`
	// Configuration parameters for the agent interaction.
	AgentConfig *CreateAgentInteractionAgentConfig `json:"agent_config,omitzero"`
	// The input for the interaction.
	Input InteractionsInput `json:"input"`
}

func (c CreateAgentInteraction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentInteraction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAgentInteraction) GetAgent() AgentOption {
	if c == nil {
		return AgentOption("")
	}
	return c.Agent
}

func (c *CreateAgentInteraction) GetStream() *bool {
	if c == nil {
		return nil
	}
	return c.Stream
}

func (c *CreateAgentInteraction) GetStore() *bool {
	if c == nil {
		return nil
	}
	return c.Store
}

func (c *CreateAgentInteraction) GetBackground() *bool {
	if c == nil {
		return nil
	}
	return c.Background
}

func (c *CreateAgentInteraction) GetSystemInstruction() *string {
	if c == nil {
		return nil
	}
	return c.SystemInstruction
}

func (c *CreateAgentInteraction) GetTools() []Tool {
	if c == nil {
		return nil
	}
	return c.Tools
}

func (c *CreateAgentInteraction) GetResponseModalities() []ResponseModality {
	if c == nil {
		return nil
	}
	return c.ResponseModalities
}

func (c *CreateAgentInteraction) GetResponseMimeType() *string {
	if c == nil {
		return nil
	}
	return c.ResponseMimeType
}

func (c *CreateAgentInteraction) GetPreviousInteractionID() *string {
	if c == nil {
		return nil
	}
	return c.PreviousInteractionID
}

func (c *CreateAgentInteraction) GetServiceTier() *ServiceTier {
	if c == nil {
		return nil
	}
	return c.ServiceTier
}

func (c *CreateAgentInteraction) GetWebhookConfig() *WebhookConfig {
	if c == nil {
		return nil
	}
	return c.WebhookConfig
}

func (c *CreateAgentInteraction) GetResponseFormat() *CreateAgentInteractionResponseFormat {
	if c == nil {
		return nil
	}
	return c.ResponseFormat
}

func (c *CreateAgentInteraction) GetEnvironment() *CreateAgentInteractionEnvironment {
	if c == nil {
		return nil
	}
	return c.Environment
}

func (c *CreateAgentInteraction) GetAgentConfig() *CreateAgentInteractionAgentConfig {
	if c == nil {
		return nil
	}
	return c.AgentConfig
}

func (c *CreateAgentInteraction) GetAgentConfigDynamic() *DynamicAgentConfig {
	if v := c.GetAgentConfig(); v != nil {
		return v.DynamicAgentConfig
	}
	return nil
}

func (c *CreateAgentInteraction) GetAgentConfigDeepResearch() *DeepResearchAgentConfig {
	if v := c.GetAgentConfig(); v != nil {
		return v.DeepResearchAgentConfig
	}
	return nil
}

func (c *CreateAgentInteraction) GetInput() InteractionsInput {
	if c == nil {
		return InteractionsInput{}
	}
	return c.Input
}
