// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type NetworkEnum string

const (
	NetworkEnumDisabled NetworkEnum = "disabled"
)

func (e NetworkEnum) ToPointer() *NetworkEnum {
	return &e
}
func (e *NetworkEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "disabled":
		*e = NetworkEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NetworkEnum: %v", v)
	}
}

type NetworkType string

const (
	NetworkTypeEnvironmentNetworkEgressAllowlist NetworkType = "EnvironmentNetworkEgressAllowlist"
	NetworkTypeNetworkEnum                       NetworkType = "network_enum"
	NetworkTypeUnknown                           NetworkType = "Unknown"
)

// Network configuration for the environment.
type Network struct {
	EnvironmentNetworkEgressAllowlist *EnvironmentNetworkEgressAllowlist `queryParam:"inline" union:"member"`
	NetworkEnum                       *NetworkEnum                       `queryParam:"inline" union:"member"`
	UnknownRaw                        json.RawMessage                    `json:"-" union:"unknown"`

	Type NetworkType
}

func CreateNetworkEnvironmentNetworkEgressAllowlist(environmentNetworkEgressAllowlist EnvironmentNetworkEgressAllowlist) Network {
	typ := NetworkTypeEnvironmentNetworkEgressAllowlist

	return Network{
		EnvironmentNetworkEgressAllowlist: &environmentNetworkEgressAllowlist,
		Type:                              typ,
	}
}

func CreateNetworkNetworkEnum(networkEnum NetworkEnum) Network {
	typ := NetworkTypeNetworkEnum

	return Network{
		NetworkEnum: &networkEnum,
		Type:        typ,
	}
}

func CreateNetworkUnknown(raw json.RawMessage) Network {
	return Network{
		UnknownRaw: raw,
		Type:       NetworkTypeUnknown,
	}
}

func (u Network) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Network) IsUnknown() bool {
	return u.Type == NetworkTypeUnknown
}

func (u *Network) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var environmentNetworkEgressAllowlist EnvironmentNetworkEgressAllowlist = EnvironmentNetworkEgressAllowlist{}
	if err := utils.UnmarshalJSON(data, &environmentNetworkEgressAllowlist, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  NetworkTypeEnvironmentNetworkEgressAllowlist,
			Value: &environmentNetworkEgressAllowlist,
		})
	}

	var networkEnum NetworkEnum = NetworkEnum("")
	if err := utils.UnmarshalJSON(data, &networkEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  NetworkTypeNetworkEnum,
			Value: &networkEnum,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = NetworkTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = NetworkTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(NetworkType)
	switch best.Type {
	case NetworkTypeEnvironmentNetworkEgressAllowlist:
		u.EnvironmentNetworkEgressAllowlist = best.Value.(*EnvironmentNetworkEgressAllowlist)
		return nil
	case NetworkTypeNetworkEnum:
		u.NetworkEnum = best.Value.(*NetworkEnum)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = NetworkTypeUnknown
	return nil
}

func (u Network) MarshalJSON() ([]byte, error) {
	if u.EnvironmentNetworkEgressAllowlist != nil {
		return utils.MarshalJSON(u.EnvironmentNetworkEgressAllowlist, "", true)
	}

	if u.NetworkEnum != nil {
		return utils.MarshalJSON(u.NetworkEnum, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Network: all fields are null")
}

// Environment - Configuration for a custom environment.
type Environment struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_   string   `const:"remote" json:"type"`
	Sources []Source `json:"sources,omitzero"`
	// Network configuration for the environment.
	Network *Network `json:"network,omitzero"`
}

func (e Environment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Environment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Environment) GetType() string {
	return "remote"
}

func (e *Environment) GetSources() []Source {
	if e == nil {
		return nil
	}
	return e.Sources
}

func (e *Environment) GetNetwork() *Network {
	if e == nil {
		return nil
	}
	return e.Network
}
