// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type FunctionResultSubcontentType string

const (
	FunctionResultSubcontentTypeText    FunctionResultSubcontentType = "text"
	FunctionResultSubcontentTypeImage   FunctionResultSubcontentType = "image"
	FunctionResultSubcontentTypeUnknown FunctionResultSubcontentType = "UNKNOWN"
)

type FunctionResultSubcontent struct {
	TextContent  *TextContent    `queryParam:"inline" union:"member"`
	ImageContent *ImageContent   `queryParam:"inline" union:"member"`
	UnknownRaw   json.RawMessage `json:"-" union:"unknown"`

	Type FunctionResultSubcontentType
}

func CreateFunctionResultSubcontentText(text TextContent) FunctionResultSubcontent {
	typ := FunctionResultSubcontentTypeText

	return FunctionResultSubcontent{
		TextContent: &text,
		Type:        typ,
	}
}

func CreateFunctionResultSubcontentImage(image ImageContent) FunctionResultSubcontent {
	typ := FunctionResultSubcontentTypeImage

	return FunctionResultSubcontent{
		ImageContent: &image,
		Type:         typ,
	}
}

func CreateFunctionResultSubcontentUnknown(raw json.RawMessage) FunctionResultSubcontent {
	return FunctionResultSubcontent{
		UnknownRaw: raw,
		Type:       FunctionResultSubcontentTypeUnknown,
	}
}

func (u FunctionResultSubcontent) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u FunctionResultSubcontent) IsUnknown() bool {
	return u.Type == FunctionResultSubcontentTypeUnknown
}

func (u *FunctionResultSubcontent) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultSubcontentTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultSubcontentTypeUnknown
		return nil
	}

	switch dis.Type {
	case "text":
		textContent := new(TextContent)
		if err := utils.UnmarshalJSON(data, &textContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type TextContent within FunctionResultSubcontent: %w", string(data), err)
		}

		u.TextContent = textContent
		u.Type = FunctionResultSubcontentTypeText
		return nil
	case "image":
		imageContent := new(ImageContent)
		if err := utils.UnmarshalJSON(data, &imageContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image) type ImageContent within FunctionResultSubcontent: %w", string(data), err)
		}

		u.ImageContent = imageContent
		u.Type = FunctionResultSubcontentTypeImage
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultSubcontentTypeUnknown
		return nil
	}

}

func (u FunctionResultSubcontent) MarshalJSON() ([]byte, error) {
	if u.TextContent != nil {
		return utils.MarshalJSON(u.TextContent, "", true)
	}

	if u.ImageContent != nil {
		return utils.MarshalJSON(u.ImageContent, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type FunctionResultSubcontent: all fields are null")
}
