// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type FunctionResultDeltaResult struct {
}

func (f FunctionResultDeltaResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionResultDeltaResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

type FunctionResultDeltaResultUnionType string

const (
	FunctionResultDeltaResultUnionTypeFunctionResultDeltaResult       FunctionResultDeltaResultUnionType = "FunctionResultDelta_result"
	FunctionResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent FunctionResultDeltaResultUnionType = "arrayOfFunctionResultSubcontent"
	FunctionResultDeltaResultUnionTypeStr                             FunctionResultDeltaResultUnionType = "str"
	FunctionResultDeltaResultUnionTypeUnknown                         FunctionResultDeltaResultUnionType = "Unknown"
)

type FunctionResultDeltaResultUnion struct {
	FunctionResultDeltaResult       *FunctionResultDeltaResult `queryParam:"inline" union:"member"`
	ArrayOfFunctionResultSubcontent []FunctionResultSubcontent `queryParam:"inline" union:"member"`
	Str                             *string                    `queryParam:"inline" union:"member"`
	UnknownRaw                      json.RawMessage            `json:"-" union:"unknown"`

	Type FunctionResultDeltaResultUnionType
}

func CreateFunctionResultDeltaResultUnionFunctionResultDeltaResult(functionResultDeltaResult FunctionResultDeltaResult) FunctionResultDeltaResultUnion {
	typ := FunctionResultDeltaResultUnionTypeFunctionResultDeltaResult

	return FunctionResultDeltaResultUnion{
		FunctionResultDeltaResult: &functionResultDeltaResult,
		Type:                      typ,
	}
}

func CreateFunctionResultDeltaResultUnionArrayOfFunctionResultSubcontent(arrayOfFunctionResultSubcontent []FunctionResultSubcontent) FunctionResultDeltaResultUnion {
	typ := FunctionResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent

	return FunctionResultDeltaResultUnion{
		ArrayOfFunctionResultSubcontent: arrayOfFunctionResultSubcontent,
		Type:                            typ,
	}
}

func CreateFunctionResultDeltaResultUnionStr(str string) FunctionResultDeltaResultUnion {
	typ := FunctionResultDeltaResultUnionTypeStr

	return FunctionResultDeltaResultUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateFunctionResultDeltaResultUnionUnknown(raw json.RawMessage) FunctionResultDeltaResultUnion {
	return FunctionResultDeltaResultUnion{
		UnknownRaw: raw,
		Type:       FunctionResultDeltaResultUnionTypeUnknown,
	}
}

func (u FunctionResultDeltaResultUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u FunctionResultDeltaResultUnion) IsUnknown() bool {
	return u.Type == FunctionResultDeltaResultUnionTypeUnknown
}

func (u *FunctionResultDeltaResultUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var functionResultDeltaResult FunctionResultDeltaResult = FunctionResultDeltaResult{}
	if err := utils.UnmarshalJSON(data, &functionResultDeltaResult, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultDeltaResultUnionTypeFunctionResultDeltaResult,
			Value: &functionResultDeltaResult,
		})
	}

	var arrayOfFunctionResultSubcontent []FunctionResultSubcontent = []FunctionResultSubcontent{}
	if err := utils.UnmarshalJSON(data, &arrayOfFunctionResultSubcontent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent,
			Value: arrayOfFunctionResultSubcontent,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultDeltaResultUnionTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultDeltaResultUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultDeltaResultUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FunctionResultDeltaResultUnionType)
	switch best.Type {
	case FunctionResultDeltaResultUnionTypeFunctionResultDeltaResult:
		u.FunctionResultDeltaResult = best.Value.(*FunctionResultDeltaResult)
		return nil
	case FunctionResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent:
		u.ArrayOfFunctionResultSubcontent = best.Value.([]FunctionResultSubcontent)
		return nil
	case FunctionResultDeltaResultUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = FunctionResultDeltaResultUnionTypeUnknown
	return nil
}

func (u FunctionResultDeltaResultUnion) MarshalJSON() ([]byte, error) {
	if u.FunctionResultDeltaResult != nil {
		return utils.MarshalJSON(u.FunctionResultDeltaResult, "", true)
	}

	if u.ArrayOfFunctionResultSubcontent != nil {
		return utils.MarshalJSON(u.ArrayOfFunctionResultSubcontent, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type FunctionResultDeltaResultUnion: all fields are null")
}

type FunctionResultDelta struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_   string  `const:"function_result" json:"type"`
	Name    *string `json:"name,omitzero"`
	IsError *bool   `json:"is_error,omitzero"`
	// Required. ID to match the ID from the function call block.
	CallID string                         `json:"call_id"`
	Result FunctionResultDeltaResultUnion `json:"result"`
}

func (f FunctionResultDelta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionResultDelta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionResultDelta) GetType() string {
	return "function_result"
}

func (f *FunctionResultDelta) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FunctionResultDelta) GetIsError() *bool {
	if f == nil {
		return nil
	}
	return f.IsError
}

func (f *FunctionResultDelta) GetCallID() string {
	if f == nil {
		return ""
	}
	return f.CallID
}

func (f *FunctionResultDelta) GetResult() FunctionResultDeltaResultUnion {
	if f == nil {
		return FunctionResultDeltaResultUnion{}
	}
	return f.Result
}
