// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type FunctionResultStepResult struct {
}

func (f FunctionResultStepResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionResultStepResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

type FunctionResultStepResultUnionType string

const (
	FunctionResultStepResultUnionTypeFunctionResultStepResult        FunctionResultStepResultUnionType = "FunctionResultStep_result"
	FunctionResultStepResultUnionTypeArrayOfFunctionResultSubcontent FunctionResultStepResultUnionType = "arrayOfFunctionResultSubcontent"
	FunctionResultStepResultUnionTypeStr                             FunctionResultStepResultUnionType = "str"
	FunctionResultStepResultUnionTypeUnknown                         FunctionResultStepResultUnionType = "Unknown"
)

// FunctionResultStepResultUnion - The result of the tool call.
type FunctionResultStepResultUnion struct {
	FunctionResultStepResult        *FunctionResultStepResult  `queryParam:"inline" union:"member"`
	ArrayOfFunctionResultSubcontent []FunctionResultSubcontent `queryParam:"inline" union:"member"`
	Str                             *string                    `queryParam:"inline" union:"member"`
	UnknownRaw                      json.RawMessage            `json:"-" union:"unknown"`

	Type FunctionResultStepResultUnionType
}

func CreateFunctionResultStepResultUnionFunctionResultStepResult(functionResultStepResult FunctionResultStepResult) FunctionResultStepResultUnion {
	typ := FunctionResultStepResultUnionTypeFunctionResultStepResult

	return FunctionResultStepResultUnion{
		FunctionResultStepResult: &functionResultStepResult,
		Type:                     typ,
	}
}

func CreateFunctionResultStepResultUnionArrayOfFunctionResultSubcontent(arrayOfFunctionResultSubcontent []FunctionResultSubcontent) FunctionResultStepResultUnion {
	typ := FunctionResultStepResultUnionTypeArrayOfFunctionResultSubcontent

	return FunctionResultStepResultUnion{
		ArrayOfFunctionResultSubcontent: arrayOfFunctionResultSubcontent,
		Type:                            typ,
	}
}

func CreateFunctionResultStepResultUnionStr(str string) FunctionResultStepResultUnion {
	typ := FunctionResultStepResultUnionTypeStr

	return FunctionResultStepResultUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateFunctionResultStepResultUnionUnknown(raw json.RawMessage) FunctionResultStepResultUnion {
	return FunctionResultStepResultUnion{
		UnknownRaw: raw,
		Type:       FunctionResultStepResultUnionTypeUnknown,
	}
}

func (u FunctionResultStepResultUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u FunctionResultStepResultUnion) IsUnknown() bool {
	return u.Type == FunctionResultStepResultUnionTypeUnknown
}

func (u *FunctionResultStepResultUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var functionResultStepResult FunctionResultStepResult = FunctionResultStepResult{}
	if err := utils.UnmarshalJSON(data, &functionResultStepResult, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultStepResultUnionTypeFunctionResultStepResult,
			Value: &functionResultStepResult,
		})
	}

	var arrayOfFunctionResultSubcontent []FunctionResultSubcontent = []FunctionResultSubcontent{}
	if err := utils.UnmarshalJSON(data, &arrayOfFunctionResultSubcontent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultStepResultUnionTypeArrayOfFunctionResultSubcontent,
			Value: arrayOfFunctionResultSubcontent,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultStepResultUnionTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultStepResultUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultStepResultUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FunctionResultStepResultUnionType)
	switch best.Type {
	case FunctionResultStepResultUnionTypeFunctionResultStepResult:
		u.FunctionResultStepResult = best.Value.(*FunctionResultStepResult)
		return nil
	case FunctionResultStepResultUnionTypeArrayOfFunctionResultSubcontent:
		u.ArrayOfFunctionResultSubcontent = best.Value.([]FunctionResultSubcontent)
		return nil
	case FunctionResultStepResultUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = FunctionResultStepResultUnionTypeUnknown
	return nil
}

func (u FunctionResultStepResultUnion) MarshalJSON() ([]byte, error) {
	if u.FunctionResultStepResult != nil {
		return utils.MarshalJSON(u.FunctionResultStepResult, "", true)
	}

	if u.ArrayOfFunctionResultSubcontent != nil {
		return utils.MarshalJSON(u.ArrayOfFunctionResultSubcontent, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type FunctionResultStepResultUnion: all fields are null")
}

// FunctionResultStep - Result of a function tool call.
type FunctionResultStep struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"function_result" json:"type"`
	// The name of the tool that was called.
	Name *string `json:"name,omitzero"`
	// Whether the tool call resulted in an error.
	IsError *bool `json:"is_error,omitzero"`
	// Required. ID to match the ID from the function call block.
	CallID string `json:"call_id"`
	// The result of the tool call.
	Result FunctionResultStepResultUnion `json:"result"`
}

func (f FunctionResultStep) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionResultStep) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionResultStep) GetType() string {
	return "function_result"
}

func (f *FunctionResultStep) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FunctionResultStep) GetIsError() *bool {
	if f == nil {
		return nil
	}
	return f.IsError
}

func (f *FunctionResultStep) GetCallID() string {
	if f == nil {
		return ""
	}
	return f.CallID
}

func (f *FunctionResultStep) GetResult() FunctionResultStepResultUnion {
	if f == nil {
		return FunctionResultStepResultUnion{}
	}
	return f.Result
}
