// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type ToolChoiceUnionType string

const (
	ToolChoiceUnionTypeToolChoiceType   ToolChoiceUnionType = "ToolChoiceType"
	ToolChoiceUnionTypeToolChoiceConfig ToolChoiceUnionType = "ToolChoiceConfig"
	ToolChoiceUnionTypeUnknown          ToolChoiceUnionType = "Unknown"
)

// ToolChoice - The tool choice configuration.
type ToolChoice struct {
	ToolChoiceType   *ToolChoiceType   `queryParam:"inline" union:"member"`
	ToolChoiceConfig *ToolChoiceConfig `queryParam:"inline" union:"member"`
	UnknownRaw       json.RawMessage   `json:"-" union:"unknown"`

	Type ToolChoiceUnionType
}

func CreateToolChoiceToolChoiceType(toolChoiceType ToolChoiceType) ToolChoice {
	typ := ToolChoiceUnionTypeToolChoiceType

	return ToolChoice{
		ToolChoiceType: &toolChoiceType,
		Type:           typ,
	}
}

func CreateToolChoiceToolChoiceConfig(toolChoiceConfig ToolChoiceConfig) ToolChoice {
	typ := ToolChoiceUnionTypeToolChoiceConfig

	return ToolChoice{
		ToolChoiceConfig: &toolChoiceConfig,
		Type:             typ,
	}
}

func CreateToolChoiceUnknown(raw json.RawMessage) ToolChoice {
	return ToolChoice{
		UnknownRaw: raw,
		Type:       ToolChoiceUnionTypeUnknown,
	}
}

func (u ToolChoice) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ToolChoice) IsUnknown() bool {
	return u.Type == ToolChoiceUnionTypeUnknown
}

func (u *ToolChoice) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var toolChoiceType ToolChoiceType = ToolChoiceType("")
	if err := utils.UnmarshalJSON(data, &toolChoiceType, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ToolChoiceUnionTypeToolChoiceType,
			Value: &toolChoiceType,
		})
	}

	var toolChoiceConfig ToolChoiceConfig = ToolChoiceConfig{}
	if err := utils.UnmarshalJSON(data, &toolChoiceConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ToolChoiceUnionTypeToolChoiceConfig,
			Value: &toolChoiceConfig,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolChoiceUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolChoiceUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ToolChoiceUnionType)
	switch best.Type {
	case ToolChoiceUnionTypeToolChoiceType:
		u.ToolChoiceType = best.Value.(*ToolChoiceType)
		return nil
	case ToolChoiceUnionTypeToolChoiceConfig:
		u.ToolChoiceConfig = best.Value.(*ToolChoiceConfig)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ToolChoiceUnionTypeUnknown
	return nil
}

func (u ToolChoice) MarshalJSON() ([]byte, error) {
	if u.ToolChoiceType != nil {
		return utils.MarshalJSON(u.ToolChoiceType, "", true)
	}

	if u.ToolChoiceConfig != nil {
		return utils.MarshalJSON(u.ToolChoiceConfig, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ToolChoice: all fields are null")
}

// GenerationConfig - Configuration parameters for model interactions.
type GenerationConfig struct {
	// Controls the randomness of the output.
	Temperature *float32 `json:"temperature,omitzero"`
	// The maximum cumulative probability of tokens to consider when sampling.
	TopP *float32 `json:"top_p,omitzero"`
	// Seed used in decoding for reproducibility.
	Seed *int `json:"seed,omitzero"`
	// A list of character sequences that will stop output interaction.
	StopSequences     []string           `json:"stop_sequences,omitzero"`
	ThinkingLevel     *ThinkingLevel     `json:"thinking_level,omitzero"`
	ThinkingSummaries *ThinkingSummaries `json:"thinking_summaries,omitzero"`
	// The maximum number of tokens to include in the response.
	MaxOutputTokens *int `json:"max_output_tokens,omitzero"`
	// Configuration for speech interaction.
	SpeechConfig []SpeechConfig `json:"speech_config,omitzero"`
	// The configuration for image interaction.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ImageConfig *ImageConfig `json:"image_config,omitzero"`
	// Configuration options for video generation.
	VideoConfig *VideoConfig `json:"video_config,omitzero"`
	// Penalizes tokens that have already appeared in the generated
	// text. A positive value encourages the model to generate more diverse and
	// less repetitive text. Valid values can range from [-2.0, 2.0].
	PresencePenalty *float32 `json:"presence_penalty,omitzero"`
	// Penalizes tokens based on their frequency in the generated text.
	// A positive value helps to reduce the repetition of words and phrases.
	// Valid values can range from [-2.0, 2.0].
	FrequencyPenalty *float32 `json:"frequency_penalty,omitzero"`
	// The tool choice configuration.
	ToolChoice *ToolChoice `json:"tool_choice,omitzero"`
}

func (g GenerationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GenerationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GenerationConfig) GetTemperature() *float32 {
	if g == nil {
		return nil
	}
	return g.Temperature
}

func (g *GenerationConfig) GetTopP() *float32 {
	if g == nil {
		return nil
	}
	return g.TopP
}

func (g *GenerationConfig) GetSeed() *int {
	if g == nil {
		return nil
	}
	return g.Seed
}

func (g *GenerationConfig) GetStopSequences() []string {
	if g == nil {
		return nil
	}
	return g.StopSequences
}

func (g *GenerationConfig) GetThinkingLevel() *ThinkingLevel {
	if g == nil {
		return nil
	}
	return g.ThinkingLevel
}

func (g *GenerationConfig) GetThinkingSummaries() *ThinkingSummaries {
	if g == nil {
		return nil
	}
	return g.ThinkingSummaries
}

func (g *GenerationConfig) GetMaxOutputTokens() *int {
	if g == nil {
		return nil
	}
	return g.MaxOutputTokens
}

func (g *GenerationConfig) GetSpeechConfig() []SpeechConfig {
	if g == nil {
		return nil
	}
	return g.SpeechConfig
}

func (g *GenerationConfig) GetImageConfig() *ImageConfig {
	if g == nil {
		return nil
	}
	return g.ImageConfig
}

func (g *GenerationConfig) GetVideoConfig() *VideoConfig {
	if g == nil {
		return nil
	}
	return g.VideoConfig
}

func (g *GenerationConfig) GetPresencePenalty() *float32 {
	if g == nil {
		return nil
	}
	return g.PresencePenalty
}

func (g *GenerationConfig) GetFrequencyPenalty() *float32 {
	if g == nil {
		return nil
	}
	return g.FrequencyPenalty
}

func (g *GenerationConfig) GetToolChoice() *ToolChoice {
	if g == nil {
		return nil
	}
	return g.ToolChoice
}
