// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"google.golang.org/genai/gaos/internal/utils"
)

// GoogleSearchResultStep - Google Search result step.
type GoogleSearchResultStep struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"google_search_result" json:"type"`
	// Required. The results of the Google Search.
	Result []GoogleSearchResult `json:"result"`
	// Whether the Google Search resulted in an error.
	IsError *bool `json:"is_error,omitzero"`
	// Required. ID to match the ID from the function call block.
	CallID string `json:"call_id"`
	// A signature hash for backend validation.
	Signature *string `json:"signature,omitzero"`
}

func (g GoogleSearchResultStep) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GoogleSearchResultStep) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GoogleSearchResultStep) GetType() string {
	return "google_search_result"
}

func (g *GoogleSearchResultStep) GetResult() []GoogleSearchResult {
	if g == nil {
		return []GoogleSearchResult{}
	}
	return g.Result
}

func (g *GoogleSearchResultStep) GetIsError() *bool {
	if g == nil {
		return nil
	}
	return g.IsError
}

func (g *GoogleSearchResultStep) GetCallID() string {
	if g == nil {
		return ""
	}
	return g.CallID
}

func (g *GoogleSearchResultStep) GetSignature() *string {
	if g == nil {
		return nil
	}
	return g.Signature
}
