// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type InteractionsInputType string

const (
	InteractionsInputTypeStr            InteractionsInputType = "str"
	InteractionsInputTypeArrayOfStep    InteractionsInputType = "arrayOfStep"
	InteractionsInputTypeArrayOfContent InteractionsInputType = "arrayOfContent"
	InteractionsInputTypeArrayOfTurn    InteractionsInputType = "arrayOfTurn"
	InteractionsInputTypeContent        InteractionsInputType = "Content"
	InteractionsInputTypeUnknown        InteractionsInputType = "Unknown"
)

// InteractionsInput - The input for the interaction.
type InteractionsInput struct {
	Str            *string         `queryParam:"inline" union:"member"`
	ArrayOfStep    []Step          `queryParam:"inline" union:"member"`
	ArrayOfContent []Content       `queryParam:"inline" union:"member"`
	ArrayOfTurn    []Turn          `queryParam:"inline" union:"member"`
	Content        *Content        `queryParam:"inline" union:"member"`
	UnknownRaw     json.RawMessage `json:"-" union:"unknown"`

	Type InteractionsInputType
}

func CreateInteractionsInputStr(str string) InteractionsInput {
	typ := InteractionsInputTypeStr

	return InteractionsInput{
		Str:  &str,
		Type: typ,
	}
}

func CreateInteractionsInputArrayOfStep(arrayOfStep []Step) InteractionsInput {
	typ := InteractionsInputTypeArrayOfStep

	return InteractionsInput{
		ArrayOfStep: arrayOfStep,
		Type:        typ,
	}
}

func CreateInteractionsInputArrayOfContent(arrayOfContent []Content) InteractionsInput {
	typ := InteractionsInputTypeArrayOfContent

	return InteractionsInput{
		ArrayOfContent: arrayOfContent,
		Type:           typ,
	}
}

func CreateInteractionsInputArrayOfTurn(arrayOfTurn []Turn) InteractionsInput {
	typ := InteractionsInputTypeArrayOfTurn

	return InteractionsInput{
		ArrayOfTurn: arrayOfTurn,
		Type:        typ,
	}
}

func CreateInteractionsInputContent(content Content) InteractionsInput {
	typ := InteractionsInputTypeContent

	return InteractionsInput{
		Content: &content,
		Type:    typ,
	}
}

func CreateInteractionsInputUnknown(raw json.RawMessage) InteractionsInput {
	return InteractionsInput{
		UnknownRaw: raw,
		Type:       InteractionsInputTypeUnknown,
	}
}

func (u InteractionsInput) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u InteractionsInput) IsUnknown() bool {
	return u.Type == InteractionsInputTypeUnknown
}

func (u *InteractionsInput) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionsInputTypeStr,
			Value: &str,
		})
	}

	var arrayOfStep []Step = []Step{}
	if err := utils.UnmarshalJSON(data, &arrayOfStep, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionsInputTypeArrayOfStep,
			Value: arrayOfStep,
		})
	}

	var arrayOfContent []Content = []Content{}
	if err := utils.UnmarshalJSON(data, &arrayOfContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionsInputTypeArrayOfContent,
			Value: arrayOfContent,
		})
	}

	var arrayOfTurn []Turn = []Turn{}
	if err := utils.UnmarshalJSON(data, &arrayOfTurn, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionsInputTypeArrayOfTurn,
			Value: arrayOfTurn,
		})
	}

	var content Content = Content{}
	if err := utils.UnmarshalJSON(data, &content, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionsInputTypeContent,
			Value: &content,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionsInputTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionsInputTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InteractionsInputType)
	switch best.Type {
	case InteractionsInputTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case InteractionsInputTypeArrayOfStep:
		u.ArrayOfStep = best.Value.([]Step)
		return nil
	case InteractionsInputTypeArrayOfContent:
		u.ArrayOfContent = best.Value.([]Content)
		return nil
	case InteractionsInputTypeArrayOfTurn:
		u.ArrayOfTurn = best.Value.([]Turn)
		return nil
	case InteractionsInputTypeContent:
		u.Content = best.Value.(*Content)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = InteractionsInputTypeUnknown
	return nil
}

func (u InteractionsInput) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStep != nil {
		return utils.MarshalJSON(u.ArrayOfStep, "", true)
	}

	if u.ArrayOfContent != nil {
		return utils.MarshalJSON(u.ArrayOfContent, "", true)
	}

	if u.ArrayOfTurn != nil {
		return utils.MarshalJSON(u.ArrayOfTurn, "", true)
	}

	if u.Content != nil {
		return utils.MarshalJSON(u.Content, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type InteractionsInput: all fields are null")
}
