// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type InteractionSSEEventType string

const (
	InteractionSSEEventTypeInteractionCreated      InteractionSSEEventType = "interaction.created"
	InteractionSSEEventTypeInteractionCompleted    InteractionSSEEventType = "interaction.completed"
	InteractionSSEEventTypeInteractionStatusUpdate InteractionSSEEventType = "interaction.status_update"
	InteractionSSEEventTypeError                   InteractionSSEEventType = "error"
	InteractionSSEEventTypeStepStart               InteractionSSEEventType = "step.start"
	InteractionSSEEventTypeStepDelta               InteractionSSEEventType = "step.delta"
	InteractionSSEEventTypeStepStop                InteractionSSEEventType = "step.stop"
	InteractionSSEEventTypeUnknown                 InteractionSSEEventType = "UNKNOWN"
)

type InteractionSSEEvent struct {
	InteractionCreatedEvent   *InteractionCreatedEvent   `queryParam:"inline" union:"member"`
	InteractionCompletedEvent *InteractionCompletedEvent `queryParam:"inline" union:"member"`
	InteractionStatusUpdate   *InteractionStatusUpdate   `queryParam:"inline" union:"member"`
	ErrorEvent                *ErrorEvent                `queryParam:"inline" union:"member"`
	StepStart                 *StepStart                 `queryParam:"inline" union:"member"`
	StepDelta                 *StepDelta                 `queryParam:"inline" union:"member"`
	StepStop                  *StepStop                  `queryParam:"inline" union:"member"`
	UnknownRaw                json.RawMessage            `json:"-" union:"unknown"`

	Type InteractionSSEEventType
}

func CreateInteractionSSEEventInteractionCreated(interactionCreated InteractionCreatedEvent) InteractionSSEEvent {
	typ := InteractionSSEEventTypeInteractionCreated

	return InteractionSSEEvent{
		InteractionCreatedEvent: &interactionCreated,
		Type:                    typ,
	}
}

func CreateInteractionSSEEventInteractionCompleted(interactionCompleted InteractionCompletedEvent) InteractionSSEEvent {
	typ := InteractionSSEEventTypeInteractionCompleted

	return InteractionSSEEvent{
		InteractionCompletedEvent: &interactionCompleted,
		Type:                      typ,
	}
}

func CreateInteractionSSEEventInteractionStatusUpdate(interactionStatusUpdate InteractionStatusUpdate) InteractionSSEEvent {
	typ := InteractionSSEEventTypeInteractionStatusUpdate

	return InteractionSSEEvent{
		InteractionStatusUpdate: &interactionStatusUpdate,
		Type:                    typ,
	}
}

func CreateInteractionSSEEventError(errorT ErrorEvent) InteractionSSEEvent {
	typ := InteractionSSEEventTypeError

	return InteractionSSEEvent{
		ErrorEvent: &errorT,
		Type:       typ,
	}
}

func CreateInteractionSSEEventStepStart(stepStart StepStart) InteractionSSEEvent {
	typ := InteractionSSEEventTypeStepStart

	return InteractionSSEEvent{
		StepStart: &stepStart,
		Type:      typ,
	}
}

func CreateInteractionSSEEventStepDelta(stepDelta StepDelta) InteractionSSEEvent {
	typ := InteractionSSEEventTypeStepDelta

	return InteractionSSEEvent{
		StepDelta: &stepDelta,
		Type:      typ,
	}
}

func CreateInteractionSSEEventStepStop(stepStop StepStop) InteractionSSEEvent {
	typ := InteractionSSEEventTypeStepStop

	return InteractionSSEEvent{
		StepStop: &stepStop,
		Type:     typ,
	}
}

func CreateInteractionSSEEventUnknown(raw json.RawMessage) InteractionSSEEvent {
	return InteractionSSEEvent{
		UnknownRaw: raw,
		Type:       InteractionSSEEventTypeUnknown,
	}
}

func (u InteractionSSEEvent) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u InteractionSSEEvent) IsUnknown() bool {
	return u.Type == InteractionSSEEventTypeUnknown
}

func (u *InteractionSSEEvent) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		EventType string `json:"event_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionSSEEventTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionSSEEventTypeUnknown
		return nil
	}

	switch dis.EventType {
	case "interaction.created":
		interactionCreatedEvent := new(InteractionCreatedEvent)
		if err := utils.UnmarshalJSON(data, &interactionCreatedEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == interaction.created) type InteractionCreatedEvent within InteractionSSEEvent: %w", string(data), err)
		}

		u.InteractionCreatedEvent = interactionCreatedEvent
		u.Type = InteractionSSEEventTypeInteractionCreated
		return nil
	case "interaction.completed":
		interactionCompletedEvent := new(InteractionCompletedEvent)
		if err := utils.UnmarshalJSON(data, &interactionCompletedEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == interaction.completed) type InteractionCompletedEvent within InteractionSSEEvent: %w", string(data), err)
		}

		u.InteractionCompletedEvent = interactionCompletedEvent
		u.Type = InteractionSSEEventTypeInteractionCompleted
		return nil
	case "interaction.status_update":
		interactionStatusUpdate := new(InteractionStatusUpdate)
		if err := utils.UnmarshalJSON(data, &interactionStatusUpdate, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == interaction.status_update) type InteractionStatusUpdate within InteractionSSEEvent: %w", string(data), err)
		}

		u.InteractionStatusUpdate = interactionStatusUpdate
		u.Type = InteractionSSEEventTypeInteractionStatusUpdate
		return nil
	case "error":
		errorEvent := new(ErrorEvent)
		if err := utils.UnmarshalJSON(data, &errorEvent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == error) type ErrorEvent within InteractionSSEEvent: %w", string(data), err)
		}

		u.ErrorEvent = errorEvent
		u.Type = InteractionSSEEventTypeError
		return nil
	case "step.start":
		stepStart := new(StepStart)
		if err := utils.UnmarshalJSON(data, &stepStart, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == step.start) type StepStart within InteractionSSEEvent: %w", string(data), err)
		}

		u.StepStart = stepStart
		u.Type = InteractionSSEEventTypeStepStart
		return nil
	case "step.delta":
		stepDelta := new(StepDelta)
		if err := utils.UnmarshalJSON(data, &stepDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == step.delta) type StepDelta within InteractionSSEEvent: %w", string(data), err)
		}

		u.StepDelta = stepDelta
		u.Type = InteractionSSEEventTypeStepDelta
		return nil
	case "step.stop":
		stepStop := new(StepStop)
		if err := utils.UnmarshalJSON(data, &stepStop, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (EventType == step.stop) type StepStop within InteractionSSEEvent: %w", string(data), err)
		}

		u.StepStop = stepStop
		u.Type = InteractionSSEEventTypeStepStop
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionSSEEventTypeUnknown
		return nil
	}

}

func (u InteractionSSEEvent) MarshalJSON() ([]byte, error) {
	if u.InteractionCreatedEvent != nil {
		return utils.MarshalJSON(u.InteractionCreatedEvent, "", true)
	}

	if u.InteractionCompletedEvent != nil {
		return utils.MarshalJSON(u.InteractionCompletedEvent, "", true)
	}

	if u.InteractionStatusUpdate != nil {
		return utils.MarshalJSON(u.InteractionStatusUpdate, "", true)
	}

	if u.ErrorEvent != nil {
		return utils.MarshalJSON(u.ErrorEvent, "", true)
	}

	if u.StepStart != nil {
		return utils.MarshalJSON(u.StepStart, "", true)
	}

	if u.StepDelta != nil {
		return utils.MarshalJSON(u.StepDelta, "", true)
	}

	if u.StepStop != nil {
		return utils.MarshalJSON(u.StepStop, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type InteractionSSEEvent: all fields are null")
}
