// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

// InteractionStatus - Required. Output only. The status of the interaction.
type InteractionStatus string

const (
	InteractionStatusInProgress     InteractionStatus = "in_progress"
	InteractionStatusRequiresAction InteractionStatus = "requires_action"
	InteractionStatusCompleted      InteractionStatus = "completed"
	InteractionStatusFailed         InteractionStatus = "failed"
	InteractionStatusCancelled      InteractionStatus = "cancelled"
	InteractionStatusIncomplete     InteractionStatus = "incomplete"
	InteractionStatusBudgetExceeded InteractionStatus = "budget_exceeded"
)

func (e InteractionStatus) ToPointer() *InteractionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InteractionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "in_progress", "requires_action", "completed", "failed", "cancelled", "incomplete", "budget_exceeded":
			return true
		}
	}
	return false
}

type InteractionResponseFormatType string

const (
	InteractionResponseFormatTypeArrayOfResponseFormat InteractionResponseFormatType = "arrayOfResponseFormat"
	InteractionResponseFormatTypeResponseFormat        InteractionResponseFormatType = "ResponseFormat"
	InteractionResponseFormatTypeUnknown               InteractionResponseFormatType = "Unknown"
)

// InteractionResponseFormat - Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
type InteractionResponseFormat struct {
	ArrayOfResponseFormat []ResponseFormat `queryParam:"inline" union:"member"`
	ResponseFormat        *ResponseFormat  `queryParam:"inline" union:"member"`
	UnknownRaw            json.RawMessage  `json:"-" union:"unknown"`

	Type InteractionResponseFormatType
}

func CreateInteractionResponseFormatArrayOfResponseFormat(arrayOfResponseFormat []ResponseFormat) InteractionResponseFormat {
	typ := InteractionResponseFormatTypeArrayOfResponseFormat

	return InteractionResponseFormat{
		ArrayOfResponseFormat: arrayOfResponseFormat,
		Type:                  typ,
	}
}

func CreateInteractionResponseFormatResponseFormat(responseFormat ResponseFormat) InteractionResponseFormat {
	typ := InteractionResponseFormatTypeResponseFormat

	return InteractionResponseFormat{
		ResponseFormat: &responseFormat,
		Type:           typ,
	}
}

func CreateInteractionResponseFormatUnknown(raw json.RawMessage) InteractionResponseFormat {
	return InteractionResponseFormat{
		UnknownRaw: raw,
		Type:       InteractionResponseFormatTypeUnknown,
	}
}

func (u InteractionResponseFormat) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u InteractionResponseFormat) IsUnknown() bool {
	return u.Type == InteractionResponseFormatTypeUnknown
}

func (u *InteractionResponseFormat) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfResponseFormat []ResponseFormat = []ResponseFormat{}
	if err := utils.UnmarshalJSON(data, &arrayOfResponseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionResponseFormatTypeArrayOfResponseFormat,
			Value: arrayOfResponseFormat,
		})
	}

	var responseFormat ResponseFormat = ResponseFormat{}
	if err := utils.UnmarshalJSON(data, &responseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionResponseFormatTypeResponseFormat,
			Value: &responseFormat,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionResponseFormatTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionResponseFormatTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InteractionResponseFormatType)
	switch best.Type {
	case InteractionResponseFormatTypeArrayOfResponseFormat:
		u.ArrayOfResponseFormat = best.Value.([]ResponseFormat)
		return nil
	case InteractionResponseFormatTypeResponseFormat:
		u.ResponseFormat = best.Value.(*ResponseFormat)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = InteractionResponseFormatTypeUnknown
	return nil
}

func (u InteractionResponseFormat) MarshalJSON() ([]byte, error) {
	if u.ArrayOfResponseFormat != nil {
		return utils.MarshalJSON(u.ArrayOfResponseFormat, "", true)
	}

	if u.ResponseFormat != nil {
		return utils.MarshalJSON(u.ResponseFormat, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type InteractionResponseFormat: all fields are null")
}

type InteractionEnvironmentType string

const (
	InteractionEnvironmentTypeStr         InteractionEnvironmentType = "str"
	InteractionEnvironmentTypeEnvironment InteractionEnvironmentType = "Environment"
	InteractionEnvironmentTypeUnknown     InteractionEnvironmentType = "Unknown"
)

// InteractionEnvironment - The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
type InteractionEnvironment struct {
	Str         *string         `queryParam:"inline" union:"member"`
	Environment *Environment    `queryParam:"inline" union:"member"`
	UnknownRaw  json.RawMessage `json:"-" union:"unknown"`

	Type InteractionEnvironmentType
}

func CreateInteractionEnvironmentStr(str string) InteractionEnvironment {
	typ := InteractionEnvironmentTypeStr

	return InteractionEnvironment{
		Str:  &str,
		Type: typ,
	}
}

func CreateInteractionEnvironmentEnvironment(environment Environment) InteractionEnvironment {
	typ := InteractionEnvironmentTypeEnvironment

	return InteractionEnvironment{
		Environment: &environment,
		Type:        typ,
	}
}

func CreateInteractionEnvironmentUnknown(raw json.RawMessage) InteractionEnvironment {
	return InteractionEnvironment{
		UnknownRaw: raw,
		Type:       InteractionEnvironmentTypeUnknown,
	}
}

func (u InteractionEnvironment) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u InteractionEnvironment) IsUnknown() bool {
	return u.Type == InteractionEnvironmentTypeUnknown
}

func (u *InteractionEnvironment) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionEnvironmentTypeStr,
			Value: &str,
		})
	}

	var environment Environment = Environment{}
	if err := utils.UnmarshalJSON(data, &environment, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InteractionEnvironmentTypeEnvironment,
			Value: &environment,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionEnvironmentTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionEnvironmentTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InteractionEnvironmentType)
	switch best.Type {
	case InteractionEnvironmentTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case InteractionEnvironmentTypeEnvironment:
		u.Environment = best.Value.(*Environment)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = InteractionEnvironmentTypeUnknown
	return nil
}

func (u InteractionEnvironment) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Environment != nil {
		return utils.MarshalJSON(u.Environment, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type InteractionEnvironment: all fields are null")
}

type InteractionAgentConfigType string

const (
	InteractionAgentConfigTypeDynamic      InteractionAgentConfigType = "dynamic"
	InteractionAgentConfigTypeDeepResearch InteractionAgentConfigType = "deep-research"
	InteractionAgentConfigTypeUnknown      InteractionAgentConfigType = "UNKNOWN"
)

// InteractionAgentConfig - Configuration parameters for the agent interaction.
type InteractionAgentConfig struct {
	DynamicAgentConfig      *DynamicAgentConfig      `queryParam:"inline" union:"member"`
	DeepResearchAgentConfig *DeepResearchAgentConfig `queryParam:"inline" union:"member"`
	UnknownRaw              json.RawMessage          `json:"-" union:"unknown"`

	Type InteractionAgentConfigType
}

func CreateInteractionAgentConfigDynamic(dynamic DynamicAgentConfig) InteractionAgentConfig {
	typ := InteractionAgentConfigTypeDynamic

	return InteractionAgentConfig{
		DynamicAgentConfig: &dynamic,
		Type:               typ,
	}
}

func CreateInteractionAgentConfigDeepResearch(deepResearch DeepResearchAgentConfig) InteractionAgentConfig {
	typ := InteractionAgentConfigTypeDeepResearch

	return InteractionAgentConfig{
		DeepResearchAgentConfig: &deepResearch,
		Type:                    typ,
	}
}

func CreateInteractionAgentConfigUnknown(raw json.RawMessage) InteractionAgentConfig {
	return InteractionAgentConfig{
		UnknownRaw: raw,
		Type:       InteractionAgentConfigTypeUnknown,
	}
}

func (u InteractionAgentConfig) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u InteractionAgentConfig) IsUnknown() bool {
	return u.Type == InteractionAgentConfigTypeUnknown
}

func (u *InteractionAgentConfig) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionAgentConfigTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionAgentConfigTypeUnknown
		return nil
	}

	switch dis.Type {
	case "dynamic":
		dynamicAgentConfig := new(DynamicAgentConfig)
		if err := utils.UnmarshalJSON(data, &dynamicAgentConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == dynamic) type DynamicAgentConfig within InteractionAgentConfig: %w", string(data), err)
		}

		u.DynamicAgentConfig = dynamicAgentConfig
		u.Type = InteractionAgentConfigTypeDynamic
		return nil
	case "deep-research":
		deepResearchAgentConfig := new(DeepResearchAgentConfig)
		if err := utils.UnmarshalJSON(data, &deepResearchAgentConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == deep-research) type DeepResearchAgentConfig within InteractionAgentConfig: %w", string(data), err)
		}

		u.DeepResearchAgentConfig = deepResearchAgentConfig
		u.Type = InteractionAgentConfigTypeDeepResearch
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = InteractionAgentConfigTypeUnknown
		return nil
	}

}

func (u InteractionAgentConfig) MarshalJSON() ([]byte, error) {
	if u.DynamicAgentConfig != nil {
		return utils.MarshalJSON(u.DynamicAgentConfig, "", true)
	}

	if u.DeepResearchAgentConfig != nil {
		return utils.MarshalJSON(u.DeepResearchAgentConfig, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type InteractionAgentConfig: all fields are null")
}

// The Interaction resource.
type Interaction struct {
	// The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
	Model *Model `json:"model,omitzero"`
	// The agent to interact with.
	Agent *AgentOption `json:"agent,omitzero"`
	// Required. Output only. A unique identifier for the interaction completion.
	ID *string `default:"" json:"id"`
	// Required. Output only. The status of the interaction.
	Status InteractionStatus `json:"status"`
	// Output only. The time at which the response was created in ISO 8601 format
	// (YYYY-MM-DDThh:mm:ssZ).
	Created *string `json:"created,omitzero"`
	// Output only. The time at which the response was last updated in ISO 8601 format
	// (YYYY-MM-DDThh:mm:ssZ).
	Updated *string `json:"updated,omitzero"`
	// System instruction for the interaction.
	SystemInstruction *string `json:"system_instruction,omitzero"`
	// A list of tool declarations the model may call during interaction.
	Tools []Tool `json:"tools,omitzero"`
	// Statistics on the interaction request's token usage.
	Usage *Usage `json:"usage,omitzero"`
	// The requested modalities of the response (TEXT, IMAGE, AUDIO).
	ResponseModalities []ResponseModality `json:"response_modalities,omitzero"`
	// The mime type of the response. This is required if response_format is set.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ResponseMimeType *string `json:"response_mime_type,omitzero"`
	// The ID of the previous interaction, if any.
	PreviousInteractionID *string `json:"previous_interaction_id,omitzero"`
	// Output only. The environment ID for the interaction. Only populated if environment
	// config is set in the request.
	EnvironmentID *string      `json:"environment_id,omitzero"`
	ServiceTier   *ServiceTier `json:"service_tier,omitzero"`
	// Message for configuring webhook events for a request.
	WebhookConfig *WebhookConfig `json:"webhook_config,omitzero"`
	// Output only. The steps that make up the interaction, when included in the response.
	Steps []Step `json:"steps,omitzero"`
	// Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
	ResponseFormat *InteractionResponseFormat `json:"response_format,omitzero"`
	// The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
	Environment *InteractionEnvironment `json:"environment,omitzero"`
	// Configuration parameters for model interactions.
	GenerationConfig *GenerationConfig `json:"generation_config,omitzero"`
	// The name of the cached content used as context to serve the prediction.
	// Note: only used in explicit caching, where users can have control over
	// caching (e.g. what content to cache) and enjoy guaranteed cost savings.
	// Format:
	// `projects/{project}/locations/{location}/cachedContents/{cachedContent}`
	CachedContent *string `json:"cached_content,omitzero"`
	// Configuration parameters for the agent interaction.
	AgentConfig *InteractionAgentConfig `json:"agent_config,omitzero"`
	// The input for the interaction.
	Input *InteractionsInput `json:"input,omitzero"`
	// Concatenated text from the last model output in response to the current request.
	//
	// Note: this is added by the SDK.
	OutputText *string `json:"output_text,omitzero"`
	// An image content block.
	OutputImage *ImageContent `json:"output_image,omitzero"`
	// An audio content block.
	OutputAudio *AudioContent `json:"output_audio,omitzero"`
	// A video content block.
	OutputVideo *VideoContent `json:"output_video,omitzero"`
}

func (i Interaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Interaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Interaction) GetModel() *Model {
	if i == nil {
		return nil
	}
	return i.Model
}

func (i *Interaction) GetAgent() *AgentOption {
	if i == nil {
		return nil
	}
	return i.Agent
}

func (i *Interaction) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *Interaction) GetStatus() InteractionStatus {
	if i == nil {
		return InteractionStatus("")
	}
	return i.Status
}

func (i *Interaction) GetCreated() *string {
	if i == nil {
		return nil
	}
	return i.Created
}

func (i *Interaction) GetUpdated() *string {
	if i == nil {
		return nil
	}
	return i.Updated
}

func (i *Interaction) GetSystemInstruction() *string {
	if i == nil {
		return nil
	}
	return i.SystemInstruction
}

func (i *Interaction) GetTools() []Tool {
	if i == nil {
		return nil
	}
	return i.Tools
}

func (i *Interaction) GetUsage() *Usage {
	if i == nil {
		return nil
	}
	return i.Usage
}

func (i *Interaction) GetResponseModalities() []ResponseModality {
	if i == nil {
		return nil
	}
	return i.ResponseModalities
}

func (i *Interaction) GetResponseMimeType() *string {
	if i == nil {
		return nil
	}
	return i.ResponseMimeType
}

func (i *Interaction) GetPreviousInteractionID() *string {
	if i == nil {
		return nil
	}
	return i.PreviousInteractionID
}

func (i *Interaction) GetEnvironmentID() *string {
	if i == nil {
		return nil
	}
	return i.EnvironmentID
}

func (i *Interaction) GetServiceTier() *ServiceTier {
	if i == nil {
		return nil
	}
	return i.ServiceTier
}

func (i *Interaction) GetWebhookConfig() *WebhookConfig {
	if i == nil {
		return nil
	}
	return i.WebhookConfig
}

func (i *Interaction) GetSteps() []Step {
	if i == nil {
		return nil
	}
	return i.Steps
}

func (i *Interaction) GetResponseFormat() *InteractionResponseFormat {
	if i == nil {
		return nil
	}
	return i.ResponseFormat
}

func (i *Interaction) GetEnvironment() *InteractionEnvironment {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *Interaction) GetGenerationConfig() *GenerationConfig {
	if i == nil {
		return nil
	}
	return i.GenerationConfig
}

func (i *Interaction) GetCachedContent() *string {
	if i == nil {
		return nil
	}
	return i.CachedContent
}

func (i *Interaction) GetAgentConfig() *InteractionAgentConfig {
	if i == nil {
		return nil
	}
	return i.AgentConfig
}

func (i *Interaction) GetAgentConfigDynamic() *DynamicAgentConfig {
	if v := i.GetAgentConfig(); v != nil {
		return v.DynamicAgentConfig
	}
	return nil
}

func (i *Interaction) GetAgentConfigDeepResearch() *DeepResearchAgentConfig {
	if v := i.GetAgentConfig(); v != nil {
		return v.DeepResearchAgentConfig
	}
	return nil
}

func (i *Interaction) GetInput() *InteractionsInput {
	if i == nil {
		return nil
	}
	return i.Input
}

func (i *Interaction) GetOutputText() *string {
	if i == nil {
		return nil
	}
	return i.OutputText
}

func (i *Interaction) GetOutputImage() *ImageContent {
	if i == nil {
		return nil
	}
	return i.OutputImage
}

func (i *Interaction) GetOutputAudio() *AudioContent {
	if i == nil {
		return nil
	}
	return i.OutputAudio
}

func (i *Interaction) GetOutputVideo() *VideoContent {
	if i == nil {
		return nil
	}
	return i.OutputVideo
}
