// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type MCPServerToolResultDeltaResult struct {
}

func (m MCPServerToolResultDeltaResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MCPServerToolResultDeltaResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

type MCPServerToolResultDeltaResultUnionType string

const (
	MCPServerToolResultDeltaResultUnionTypeMCPServerToolResultDeltaResult  MCPServerToolResultDeltaResultUnionType = "MCPServerToolResultDelta_result"
	MCPServerToolResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent MCPServerToolResultDeltaResultUnionType = "arrayOfFunctionResultSubcontent"
	MCPServerToolResultDeltaResultUnionTypeStr                             MCPServerToolResultDeltaResultUnionType = "str"
	MCPServerToolResultDeltaResultUnionTypeUnknown                         MCPServerToolResultDeltaResultUnionType = "Unknown"
)

type MCPServerToolResultDeltaResultUnion struct {
	MCPServerToolResultDeltaResult  *MCPServerToolResultDeltaResult `queryParam:"inline" union:"member"`
	ArrayOfFunctionResultSubcontent []FunctionResultSubcontent      `queryParam:"inline" union:"member"`
	Str                             *string                         `queryParam:"inline" union:"member"`
	UnknownRaw                      json.RawMessage                 `json:"-" union:"unknown"`

	Type MCPServerToolResultDeltaResultUnionType
}

func CreateMCPServerToolResultDeltaResultUnionMCPServerToolResultDeltaResult(mcpServerToolResultDeltaResult MCPServerToolResultDeltaResult) MCPServerToolResultDeltaResultUnion {
	typ := MCPServerToolResultDeltaResultUnionTypeMCPServerToolResultDeltaResult

	return MCPServerToolResultDeltaResultUnion{
		MCPServerToolResultDeltaResult: &mcpServerToolResultDeltaResult,
		Type:                           typ,
	}
}

func CreateMCPServerToolResultDeltaResultUnionArrayOfFunctionResultSubcontent(arrayOfFunctionResultSubcontent []FunctionResultSubcontent) MCPServerToolResultDeltaResultUnion {
	typ := MCPServerToolResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent

	return MCPServerToolResultDeltaResultUnion{
		ArrayOfFunctionResultSubcontent: arrayOfFunctionResultSubcontent,
		Type:                            typ,
	}
}

func CreateMCPServerToolResultDeltaResultUnionStr(str string) MCPServerToolResultDeltaResultUnion {
	typ := MCPServerToolResultDeltaResultUnionTypeStr

	return MCPServerToolResultDeltaResultUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateMCPServerToolResultDeltaResultUnionUnknown(raw json.RawMessage) MCPServerToolResultDeltaResultUnion {
	return MCPServerToolResultDeltaResultUnion{
		UnknownRaw: raw,
		Type:       MCPServerToolResultDeltaResultUnionTypeUnknown,
	}
}

func (u MCPServerToolResultDeltaResultUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u MCPServerToolResultDeltaResultUnion) IsUnknown() bool {
	return u.Type == MCPServerToolResultDeltaResultUnionTypeUnknown
}

func (u *MCPServerToolResultDeltaResultUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var mcpServerToolResultDeltaResult MCPServerToolResultDeltaResult = MCPServerToolResultDeltaResult{}
	if err := utils.UnmarshalJSON(data, &mcpServerToolResultDeltaResult, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultDeltaResultUnionTypeMCPServerToolResultDeltaResult,
			Value: &mcpServerToolResultDeltaResult,
		})
	}

	var arrayOfFunctionResultSubcontent []FunctionResultSubcontent = []FunctionResultSubcontent{}
	if err := utils.UnmarshalJSON(data, &arrayOfFunctionResultSubcontent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent,
			Value: arrayOfFunctionResultSubcontent,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultDeltaResultUnionTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = MCPServerToolResultDeltaResultUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = MCPServerToolResultDeltaResultUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MCPServerToolResultDeltaResultUnionType)
	switch best.Type {
	case MCPServerToolResultDeltaResultUnionTypeMCPServerToolResultDeltaResult:
		u.MCPServerToolResultDeltaResult = best.Value.(*MCPServerToolResultDeltaResult)
		return nil
	case MCPServerToolResultDeltaResultUnionTypeArrayOfFunctionResultSubcontent:
		u.ArrayOfFunctionResultSubcontent = best.Value.([]FunctionResultSubcontent)
		return nil
	case MCPServerToolResultDeltaResultUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = MCPServerToolResultDeltaResultUnionTypeUnknown
	return nil
}

func (u MCPServerToolResultDeltaResultUnion) MarshalJSON() ([]byte, error) {
	if u.MCPServerToolResultDeltaResult != nil {
		return utils.MarshalJSON(u.MCPServerToolResultDeltaResult, "", true)
	}

	if u.ArrayOfFunctionResultSubcontent != nil {
		return utils.MarshalJSON(u.ArrayOfFunctionResultSubcontent, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type MCPServerToolResultDeltaResultUnion: all fields are null")
}

type MCPServerToolResultDelta struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_      string                              `const:"mcp_server_tool_result" json:"type"`
	Name       *string                             `json:"name,omitzero"`
	ServerName *string                             `json:"server_name,omitzero"`
	Result     MCPServerToolResultDeltaResultUnion `json:"result"`
}

func (m MCPServerToolResultDelta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MCPServerToolResultDelta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MCPServerToolResultDelta) GetType() string {
	return "mcp_server_tool_result"
}

func (m *MCPServerToolResultDelta) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MCPServerToolResultDelta) GetServerName() *string {
	if m == nil {
		return nil
	}
	return m.ServerName
}

func (m *MCPServerToolResultDelta) GetResult() MCPServerToolResultDeltaResultUnion {
	if m == nil {
		return MCPServerToolResultDeltaResultUnion{}
	}
	return m.Result
}
