// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

// Model - The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
type Model string

const (
	// ModelGemini25ComputerUsePreview102025 An agentic capability model designed for direct interface interaction, allowing Gemini to perceive and navigate digital environments.
	ModelGemini25ComputerUsePreview102025 Model = "gemini-2.5-computer-use-preview-10-2025"
	// ModelGemini25Flash Our first hybrid reasoning model which supports a 1M token context window and has thinking budgets.
	ModelGemini25Flash Model = "gemini-2.5-flash"
	// ModelGemini25FlashImage Our native image generation model, optimized for speed, flexibility, and contextual understanding. Text input and output is priced the same as 2.5 Flash.
	ModelGemini25FlashImage Model = "gemini-2.5-flash-image"
	// ModelGemini25FlashLite Our smallest and most cost effective model, built for at scale usage.
	ModelGemini25FlashLite Model = "gemini-2.5-flash-lite"
	// ModelGemini25FlashLitePreview092025 The latest model based on Gemini 2.5 Flash lite optimized for cost-efficiency, high throughput and high quality.
	ModelGemini25FlashLitePreview092025 Model = "gemini-2.5-flash-lite-preview-09-2025"
	// ModelGemini25FlashNativeAudioPreview122025 Our native audio models optimized for higher quality audio outputs with better pacing, voice naturalness, verbosity, and mood.
	ModelGemini25FlashNativeAudioPreview122025 Model = "gemini-2.5-flash-native-audio-preview-12-2025"
	// ModelGemini25FlashPreview092025 The latest model based on the 2.5 Flash model. 2.5 Flash Preview is best for large scale processing, low-latency, high volume tasks that require thinking, and agentic use cases.
	ModelGemini25FlashPreview092025 Model = "gemini-2.5-flash-preview-09-2025"
	// ModelGemini25FlashPreviewTts Our 2.5 Flash text-to-speech model optimized for powerful, low-latency controllable speech generation.
	ModelGemini25FlashPreviewTts Model = "gemini-2.5-flash-preview-tts"
	// ModelGemini25Pro Our state-of-the-art multipurpose model, which excels at coding and complex reasoning tasks.
	ModelGemini25Pro Model = "gemini-2.5-pro"
	// ModelGemini25ProPreviewTts Our 2.5 Pro text-to-speech audio model optimized for powerful, low-latency speech generation for more natural outputs and easier to steer prompts.
	ModelGemini25ProPreviewTts Model = "gemini-2.5-pro-preview-tts"
	// ModelGemini3FlashPreview Our most intelligent model built for speed, combining frontier intelligence with superior search and grounding.
	ModelGemini3FlashPreview Model = "gemini-3-flash-preview"
	// ModelGemini3ProImagePreview State-of-the-art image generation and editing model.
	ModelGemini3ProImagePreview Model = "gemini-3-pro-image-preview"
	// ModelGemini3ProPreview Our most intelligent model with SOTA reasoning and multimodal understanding, and powerful agentic and vibe coding capabilities.
	ModelGemini3ProPreview Model = "gemini-3-pro-preview"
	// ModelGemini31ProPreview Our latest SOTA reasoning model with unprecedented depth and nuance, and powerful multimodal understanding and coding capabilities.
	ModelGemini31ProPreview Model = "gemini-3.1-pro-preview"
	// ModelGemini31FlashImagePreview Pro-level visual intelligence with Flash-speed efficiency and reality-grounded generation capabilities.
	ModelGemini31FlashImagePreview Model = "gemini-3.1-flash-image-preview"
	// ModelGemini31FlashLite Our most cost-efficient model, optimized for high-volume agentic tasks, translation, and simple data processing.
	ModelGemini31FlashLite Model = "gemini-3.1-flash-lite"
	// ModelGemini31FlashLitePreview Our most cost-efficient model, optimized for high-volume agentic tasks, translation, and simple data processing.
	ModelGemini31FlashLitePreview Model = "gemini-3.1-flash-lite-preview"
	// ModelGemini31FlashTtsPreview Gemini 3.1 Flash TTS: Powerful, low-latency speech generation. Enjoy natural outputs, steerable prompts, and new expressive audio tags for precise narration control.
	ModelGemini31FlashTtsPreview Model = "gemini-3.1-flash-tts-preview"
	// ModelGemini35Flash Our most intelligent model for sustained frontier performance in agentic and coding tasks.
	ModelGemini35Flash Model = "gemini-3.5-flash"
	// ModelLyria3ClipPreview Our low-latency, music generation model optimized for high-fidelity audio clips and precise rhythmic control.
	ModelLyria3ClipPreview Model = "lyria-3-clip-preview"
	// ModelLyria3ProPreview Our advanced, full-song generative model with deep compositional understanding, optimized for precise structural control and complex transitions across diverse musical styles.
	ModelLyria3ProPreview Model = "lyria-3-pro-preview"
)

func (e Model) ToPointer() *Model {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Model) IsExact() bool {
	if e != nil {
		switch *e {
		case "gemini-2.5-computer-use-preview-10-2025", "gemini-2.5-flash", "gemini-2.5-flash-image", "gemini-2.5-flash-lite", "gemini-2.5-flash-lite-preview-09-2025", "gemini-2.5-flash-native-audio-preview-12-2025", "gemini-2.5-flash-preview-09-2025", "gemini-2.5-flash-preview-tts", "gemini-2.5-pro", "gemini-2.5-pro-preview-tts", "gemini-3-flash-preview", "gemini-3-pro-image-preview", "gemini-3-pro-preview", "gemini-3.1-pro-preview", "gemini-3.1-flash-image-preview", "gemini-3.1-flash-lite", "gemini-3.1-flash-lite-preview", "gemini-3.1-flash-tts-preview", "gemini-3.5-flash", "lyria-3-clip-preview", "lyria-3-pro-preview":
			return true
		}
	}
	return false
}
