// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type ResponseFormatType string

const (
	ResponseFormatTypeAudioResponseFormat ResponseFormatType = "AudioResponseFormat"
	ResponseFormatTypeTextResponseFormat  ResponseFormatType = "TextResponseFormat"
	ResponseFormatTypeImageResponseFormat ResponseFormatType = "ImageResponseFormat"
	ResponseFormatTypeVideoResponseFormat ResponseFormatType = "VideoResponseFormat"
	ResponseFormatTypeMapOfAny            ResponseFormatType = "mapOfAny"
	ResponseFormatTypeUnknown             ResponseFormatType = "Unknown"
)

type ResponseFormat struct {
	AudioResponseFormat *AudioResponseFormat `queryParam:"inline" union:"member"`
	TextResponseFormat  *TextResponseFormat  `queryParam:"inline" union:"member"`
	ImageResponseFormat *ImageResponseFormat `queryParam:"inline" union:"member"`
	VideoResponseFormat *VideoResponseFormat `queryParam:"inline" union:"member"`
	MapOfAny            map[string]any       `queryParam:"inline" union:"member"`
	UnknownRaw          json.RawMessage      `json:"-" union:"unknown"`

	Type ResponseFormatType
}

func CreateResponseFormatAudioResponseFormat(audioResponseFormat AudioResponseFormat) ResponseFormat {
	typ := ResponseFormatTypeAudioResponseFormat

	return ResponseFormat{
		AudioResponseFormat: &audioResponseFormat,
		Type:                typ,
	}
}

func CreateResponseFormatTextResponseFormat(textResponseFormat TextResponseFormat) ResponseFormat {
	typ := ResponseFormatTypeTextResponseFormat

	return ResponseFormat{
		TextResponseFormat: &textResponseFormat,
		Type:               typ,
	}
}

func CreateResponseFormatImageResponseFormat(imageResponseFormat ImageResponseFormat) ResponseFormat {
	typ := ResponseFormatTypeImageResponseFormat

	return ResponseFormat{
		ImageResponseFormat: &imageResponseFormat,
		Type:                typ,
	}
}

func CreateResponseFormatVideoResponseFormat(videoResponseFormat VideoResponseFormat) ResponseFormat {
	typ := ResponseFormatTypeVideoResponseFormat

	return ResponseFormat{
		VideoResponseFormat: &videoResponseFormat,
		Type:                typ,
	}
}

func CreateResponseFormatMapOfAny(mapOfAny map[string]any) ResponseFormat {
	typ := ResponseFormatTypeMapOfAny

	return ResponseFormat{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateResponseFormatUnknown(raw json.RawMessage) ResponseFormat {
	return ResponseFormat{
		UnknownRaw: raw,
		Type:       ResponseFormatTypeUnknown,
	}
}

func (u ResponseFormat) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ResponseFormat) IsUnknown() bool {
	return u.Type == ResponseFormatTypeUnknown
}

func (u *ResponseFormat) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var audioResponseFormat AudioResponseFormat = AudioResponseFormat{}
	if err := utils.UnmarshalJSON(data, &audioResponseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseFormatTypeAudioResponseFormat,
			Value: &audioResponseFormat,
		})
	}

	var textResponseFormat TextResponseFormat = TextResponseFormat{}
	if err := utils.UnmarshalJSON(data, &textResponseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseFormatTypeTextResponseFormat,
			Value: &textResponseFormat,
		})
	}

	var imageResponseFormat ImageResponseFormat = ImageResponseFormat{}
	if err := utils.UnmarshalJSON(data, &imageResponseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseFormatTypeImageResponseFormat,
			Value: &imageResponseFormat,
		})
	}

	var videoResponseFormat VideoResponseFormat = VideoResponseFormat{}
	if err := utils.UnmarshalJSON(data, &videoResponseFormat, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseFormatTypeVideoResponseFormat,
			Value: &videoResponseFormat,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResponseFormatTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ResponseFormatTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ResponseFormatTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ResponseFormatType)
	switch best.Type {
	case ResponseFormatTypeAudioResponseFormat:
		u.AudioResponseFormat = best.Value.(*AudioResponseFormat)
		return nil
	case ResponseFormatTypeTextResponseFormat:
		u.TextResponseFormat = best.Value.(*TextResponseFormat)
		return nil
	case ResponseFormatTypeImageResponseFormat:
		u.ImageResponseFormat = best.Value.(*ImageResponseFormat)
		return nil
	case ResponseFormatTypeVideoResponseFormat:
		u.VideoResponseFormat = best.Value.(*VideoResponseFormat)
		return nil
	case ResponseFormatTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ResponseFormatTypeUnknown
	return nil
}

func (u ResponseFormat) MarshalJSON() ([]byte, error) {
	if u.AudioResponseFormat != nil {
		return utils.MarshalJSON(u.AudioResponseFormat, "", true)
	}

	if u.TextResponseFormat != nil {
		return utils.MarshalJSON(u.TextResponseFormat, "", true)
	}

	if u.ImageResponseFormat != nil {
		return utils.MarshalJSON(u.ImageResponseFormat, "", true)
	}

	if u.VideoResponseFormat != nil {
		return utils.MarshalJSON(u.VideoResponseFormat, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ResponseFormat: all fields are null")
}
