// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type StepDeltaDataType string

const (
	StepDeltaDataTypeText                StepDeltaDataType = "text"
	StepDeltaDataTypeImage               StepDeltaDataType = "image"
	StepDeltaDataTypeAudio               StepDeltaDataType = "audio"
	StepDeltaDataTypeDocument            StepDeltaDataType = "document"
	StepDeltaDataTypeVideo               StepDeltaDataType = "video"
	StepDeltaDataTypeThoughtSummary      StepDeltaDataType = "thought_summary"
	StepDeltaDataTypeThoughtSignature    StepDeltaDataType = "thought_signature"
	StepDeltaDataTypeTextAnnotationDelta StepDeltaDataType = "text_annotation_delta"
	StepDeltaDataTypeArgumentsDelta      StepDeltaDataType = "arguments_delta"
	StepDeltaDataTypeCodeExecutionCall   StepDeltaDataType = "code_execution_call"
	StepDeltaDataTypeURLContextCall      StepDeltaDataType = "url_context_call"
	StepDeltaDataTypeGoogleSearchCall    StepDeltaDataType = "google_search_call"
	StepDeltaDataTypeMcpServerToolCall   StepDeltaDataType = "mcp_server_tool_call"
	StepDeltaDataTypeFileSearchCall      StepDeltaDataType = "file_search_call"
	StepDeltaDataTypeGoogleMapsCall      StepDeltaDataType = "google_maps_call"
	StepDeltaDataTypeCodeExecutionResult StepDeltaDataType = "code_execution_result"
	StepDeltaDataTypeURLContextResult    StepDeltaDataType = "url_context_result"
	StepDeltaDataTypeGoogleSearchResult  StepDeltaDataType = "google_search_result"
	StepDeltaDataTypeMcpServerToolResult StepDeltaDataType = "mcp_server_tool_result"
	StepDeltaDataTypeFileSearchResult    StepDeltaDataType = "file_search_result"
	StepDeltaDataTypeGoogleMapsResult    StepDeltaDataType = "google_maps_result"
	StepDeltaDataTypeFunctionResult      StepDeltaDataType = "function_result"
	StepDeltaDataTypeUnknown             StepDeltaDataType = "UNKNOWN"
)

type StepDeltaData struct {
	TextDelta                *TextDelta                `queryParam:"inline" union:"member"`
	ImageDelta               *ImageDelta               `queryParam:"inline" union:"member"`
	AudioDelta               *AudioDelta               `queryParam:"inline" union:"member"`
	DocumentDelta            *DocumentDelta            `queryParam:"inline" union:"member"`
	VideoDelta               *VideoDelta               `queryParam:"inline" union:"member"`
	ThoughtSummaryDelta      *ThoughtSummaryDelta      `queryParam:"inline" union:"member"`
	ThoughtSignatureDelta    *ThoughtSignatureDelta    `queryParam:"inline" union:"member"`
	TextAnnotationDelta      *TextAnnotationDelta      `queryParam:"inline" union:"member"`
	ArgumentsDelta           *ArgumentsDelta           `queryParam:"inline" union:"member"`
	CodeExecutionCallDelta   *CodeExecutionCallDelta   `queryParam:"inline" union:"member"`
	URLContextCallDelta      *URLContextCallDelta      `queryParam:"inline" union:"member"`
	GoogleSearchCallDelta    *GoogleSearchCallDelta    `queryParam:"inline" union:"member"`
	MCPServerToolCallDelta   *MCPServerToolCallDelta   `queryParam:"inline" union:"member"`
	FileSearchCallDelta      *FileSearchCallDelta      `queryParam:"inline" union:"member"`
	GoogleMapsCallDelta      *GoogleMapsCallDelta      `queryParam:"inline" union:"member"`
	CodeExecutionResultDelta *CodeExecutionResultDelta `queryParam:"inline" union:"member"`
	URLContextResultDelta    *URLContextResultDelta    `queryParam:"inline" union:"member"`
	GoogleSearchResultDelta  *GoogleSearchResultDelta  `queryParam:"inline" union:"member"`
	MCPServerToolResultDelta *MCPServerToolResultDelta `queryParam:"inline" union:"member"`
	FileSearchResultDelta    *FileSearchResultDelta    `queryParam:"inline" union:"member"`
	GoogleMapsResultDelta    *GoogleMapsResultDelta    `queryParam:"inline" union:"member"`
	FunctionResultDelta      *FunctionResultDelta      `queryParam:"inline" union:"member"`
	UnknownRaw               json.RawMessage           `json:"-" union:"unknown"`

	Type StepDeltaDataType
}

func CreateStepDeltaDataText(text TextDelta) StepDeltaData {
	typ := StepDeltaDataTypeText

	return StepDeltaData{
		TextDelta: &text,
		Type:      typ,
	}
}

func CreateStepDeltaDataImage(image ImageDelta) StepDeltaData {
	typ := StepDeltaDataTypeImage

	return StepDeltaData{
		ImageDelta: &image,
		Type:       typ,
	}
}

func CreateStepDeltaDataAudio(audio AudioDelta) StepDeltaData {
	typ := StepDeltaDataTypeAudio

	return StepDeltaData{
		AudioDelta: &audio,
		Type:       typ,
	}
}

func CreateStepDeltaDataDocument(document DocumentDelta) StepDeltaData {
	typ := StepDeltaDataTypeDocument

	return StepDeltaData{
		DocumentDelta: &document,
		Type:          typ,
	}
}

func CreateStepDeltaDataVideo(video VideoDelta) StepDeltaData {
	typ := StepDeltaDataTypeVideo

	return StepDeltaData{
		VideoDelta: &video,
		Type:       typ,
	}
}

func CreateStepDeltaDataThoughtSummary(thoughtSummary ThoughtSummaryDelta) StepDeltaData {
	typ := StepDeltaDataTypeThoughtSummary

	return StepDeltaData{
		ThoughtSummaryDelta: &thoughtSummary,
		Type:                typ,
	}
}

func CreateStepDeltaDataThoughtSignature(thoughtSignature ThoughtSignatureDelta) StepDeltaData {
	typ := StepDeltaDataTypeThoughtSignature

	return StepDeltaData{
		ThoughtSignatureDelta: &thoughtSignature,
		Type:                  typ,
	}
}

func CreateStepDeltaDataTextAnnotationDelta(textAnnotationDelta TextAnnotationDelta) StepDeltaData {
	typ := StepDeltaDataTypeTextAnnotationDelta

	return StepDeltaData{
		TextAnnotationDelta: &textAnnotationDelta,
		Type:                typ,
	}
}

func CreateStepDeltaDataArgumentsDelta(argumentsDelta ArgumentsDelta) StepDeltaData {
	typ := StepDeltaDataTypeArgumentsDelta

	return StepDeltaData{
		ArgumentsDelta: &argumentsDelta,
		Type:           typ,
	}
}

func CreateStepDeltaDataCodeExecutionCall(codeExecutionCall CodeExecutionCallDelta) StepDeltaData {
	typ := StepDeltaDataTypeCodeExecutionCall

	return StepDeltaData{
		CodeExecutionCallDelta: &codeExecutionCall,
		Type:                   typ,
	}
}

func CreateStepDeltaDataURLContextCall(urlContextCall URLContextCallDelta) StepDeltaData {
	typ := StepDeltaDataTypeURLContextCall

	return StepDeltaData{
		URLContextCallDelta: &urlContextCall,
		Type:                typ,
	}
}

func CreateStepDeltaDataGoogleSearchCall(googleSearchCall GoogleSearchCallDelta) StepDeltaData {
	typ := StepDeltaDataTypeGoogleSearchCall

	return StepDeltaData{
		GoogleSearchCallDelta: &googleSearchCall,
		Type:                  typ,
	}
}

func CreateStepDeltaDataMcpServerToolCall(mcpServerToolCall MCPServerToolCallDelta) StepDeltaData {
	typ := StepDeltaDataTypeMcpServerToolCall

	return StepDeltaData{
		MCPServerToolCallDelta: &mcpServerToolCall,
		Type:                   typ,
	}
}

func CreateStepDeltaDataFileSearchCall(fileSearchCall FileSearchCallDelta) StepDeltaData {
	typ := StepDeltaDataTypeFileSearchCall

	return StepDeltaData{
		FileSearchCallDelta: &fileSearchCall,
		Type:                typ,
	}
}

func CreateStepDeltaDataGoogleMapsCall(googleMapsCall GoogleMapsCallDelta) StepDeltaData {
	typ := StepDeltaDataTypeGoogleMapsCall

	return StepDeltaData{
		GoogleMapsCallDelta: &googleMapsCall,
		Type:                typ,
	}
}

func CreateStepDeltaDataCodeExecutionResult(codeExecutionResult CodeExecutionResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeCodeExecutionResult

	return StepDeltaData{
		CodeExecutionResultDelta: &codeExecutionResult,
		Type:                     typ,
	}
}

func CreateStepDeltaDataURLContextResult(urlContextResult URLContextResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeURLContextResult

	return StepDeltaData{
		URLContextResultDelta: &urlContextResult,
		Type:                  typ,
	}
}

func CreateStepDeltaDataGoogleSearchResult(googleSearchResult GoogleSearchResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeGoogleSearchResult

	return StepDeltaData{
		GoogleSearchResultDelta: &googleSearchResult,
		Type:                    typ,
	}
}

func CreateStepDeltaDataMcpServerToolResult(mcpServerToolResult MCPServerToolResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeMcpServerToolResult

	return StepDeltaData{
		MCPServerToolResultDelta: &mcpServerToolResult,
		Type:                     typ,
	}
}

func CreateStepDeltaDataFileSearchResult(fileSearchResult FileSearchResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeFileSearchResult

	return StepDeltaData{
		FileSearchResultDelta: &fileSearchResult,
		Type:                  typ,
	}
}

func CreateStepDeltaDataGoogleMapsResult(googleMapsResult GoogleMapsResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeGoogleMapsResult

	return StepDeltaData{
		GoogleMapsResultDelta: &googleMapsResult,
		Type:                  typ,
	}
}

func CreateStepDeltaDataFunctionResult(functionResult FunctionResultDelta) StepDeltaData {
	typ := StepDeltaDataTypeFunctionResult

	return StepDeltaData{
		FunctionResultDelta: &functionResult,
		Type:                typ,
	}
}

func CreateStepDeltaDataUnknown(raw json.RawMessage) StepDeltaData {
	return StepDeltaData{
		UnknownRaw: raw,
		Type:       StepDeltaDataTypeUnknown,
	}
}

func (u StepDeltaData) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u StepDeltaData) IsUnknown() bool {
	return u.Type == StepDeltaDataTypeUnknown
}

func (u *StepDeltaData) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StepDeltaDataTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StepDeltaDataTypeUnknown
		return nil
	}

	switch dis.Type {
	case "text":
		textDelta := new(TextDelta)
		if err := utils.UnmarshalJSON(data, &textDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type TextDelta within StepDeltaData: %w", string(data), err)
		}

		u.TextDelta = textDelta
		u.Type = StepDeltaDataTypeText
		return nil
	case "image":
		imageDelta := new(ImageDelta)
		if err := utils.UnmarshalJSON(data, &imageDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == image) type ImageDelta within StepDeltaData: %w", string(data), err)
		}

		u.ImageDelta = imageDelta
		u.Type = StepDeltaDataTypeImage
		return nil
	case "audio":
		audioDelta := new(AudioDelta)
		if err := utils.UnmarshalJSON(data, &audioDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == audio) type AudioDelta within StepDeltaData: %w", string(data), err)
		}

		u.AudioDelta = audioDelta
		u.Type = StepDeltaDataTypeAudio
		return nil
	case "document":
		documentDelta := new(DocumentDelta)
		if err := utils.UnmarshalJSON(data, &documentDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == document) type DocumentDelta within StepDeltaData: %w", string(data), err)
		}

		u.DocumentDelta = documentDelta
		u.Type = StepDeltaDataTypeDocument
		return nil
	case "video":
		videoDelta := new(VideoDelta)
		if err := utils.UnmarshalJSON(data, &videoDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == video) type VideoDelta within StepDeltaData: %w", string(data), err)
		}

		u.VideoDelta = videoDelta
		u.Type = StepDeltaDataTypeVideo
		return nil
	case "thought_summary":
		thoughtSummaryDelta := new(ThoughtSummaryDelta)
		if err := utils.UnmarshalJSON(data, &thoughtSummaryDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == thought_summary) type ThoughtSummaryDelta within StepDeltaData: %w", string(data), err)
		}

		u.ThoughtSummaryDelta = thoughtSummaryDelta
		u.Type = StepDeltaDataTypeThoughtSummary
		return nil
	case "thought_signature":
		thoughtSignatureDelta := new(ThoughtSignatureDelta)
		if err := utils.UnmarshalJSON(data, &thoughtSignatureDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == thought_signature) type ThoughtSignatureDelta within StepDeltaData: %w", string(data), err)
		}

		u.ThoughtSignatureDelta = thoughtSignatureDelta
		u.Type = StepDeltaDataTypeThoughtSignature
		return nil
	case "text_annotation_delta":
		textAnnotationDelta := new(TextAnnotationDelta)
		if err := utils.UnmarshalJSON(data, &textAnnotationDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text_annotation_delta) type TextAnnotationDelta within StepDeltaData: %w", string(data), err)
		}

		u.TextAnnotationDelta = textAnnotationDelta
		u.Type = StepDeltaDataTypeTextAnnotationDelta
		return nil
	case "arguments_delta":
		argumentsDelta := new(ArgumentsDelta)
		if err := utils.UnmarshalJSON(data, &argumentsDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == arguments_delta) type ArgumentsDelta within StepDeltaData: %w", string(data), err)
		}

		u.ArgumentsDelta = argumentsDelta
		u.Type = StepDeltaDataTypeArgumentsDelta
		return nil
	case "code_execution_call":
		codeExecutionCallDelta := new(CodeExecutionCallDelta)
		if err := utils.UnmarshalJSON(data, &codeExecutionCallDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_call) type CodeExecutionCallDelta within StepDeltaData: %w", string(data), err)
		}

		u.CodeExecutionCallDelta = codeExecutionCallDelta
		u.Type = StepDeltaDataTypeCodeExecutionCall
		return nil
	case "url_context_call":
		urlContextCallDelta := new(URLContextCallDelta)
		if err := utils.UnmarshalJSON(data, &urlContextCallDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == url_context_call) type URLContextCallDelta within StepDeltaData: %w", string(data), err)
		}

		u.URLContextCallDelta = urlContextCallDelta
		u.Type = StepDeltaDataTypeURLContextCall
		return nil
	case "google_search_call":
		googleSearchCallDelta := new(GoogleSearchCallDelta)
		if err := utils.UnmarshalJSON(data, &googleSearchCallDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_search_call) type GoogleSearchCallDelta within StepDeltaData: %w", string(data), err)
		}

		u.GoogleSearchCallDelta = googleSearchCallDelta
		u.Type = StepDeltaDataTypeGoogleSearchCall
		return nil
	case "mcp_server_tool_call":
		mcpServerToolCallDelta := new(MCPServerToolCallDelta)
		if err := utils.UnmarshalJSON(data, &mcpServerToolCallDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mcp_server_tool_call) type MCPServerToolCallDelta within StepDeltaData: %w", string(data), err)
		}

		u.MCPServerToolCallDelta = mcpServerToolCallDelta
		u.Type = StepDeltaDataTypeMcpServerToolCall
		return nil
	case "file_search_call":
		fileSearchCallDelta := new(FileSearchCallDelta)
		if err := utils.UnmarshalJSON(data, &fileSearchCallDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_search_call) type FileSearchCallDelta within StepDeltaData: %w", string(data), err)
		}

		u.FileSearchCallDelta = fileSearchCallDelta
		u.Type = StepDeltaDataTypeFileSearchCall
		return nil
	case "google_maps_call":
		googleMapsCallDelta := new(GoogleMapsCallDelta)
		if err := utils.UnmarshalJSON(data, &googleMapsCallDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_maps_call) type GoogleMapsCallDelta within StepDeltaData: %w", string(data), err)
		}

		u.GoogleMapsCallDelta = googleMapsCallDelta
		u.Type = StepDeltaDataTypeGoogleMapsCall
		return nil
	case "code_execution_result":
		codeExecutionResultDelta := new(CodeExecutionResultDelta)
		if err := utils.UnmarshalJSON(data, &codeExecutionResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_result) type CodeExecutionResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.CodeExecutionResultDelta = codeExecutionResultDelta
		u.Type = StepDeltaDataTypeCodeExecutionResult
		return nil
	case "url_context_result":
		urlContextResultDelta := new(URLContextResultDelta)
		if err := utils.UnmarshalJSON(data, &urlContextResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == url_context_result) type URLContextResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.URLContextResultDelta = urlContextResultDelta
		u.Type = StepDeltaDataTypeURLContextResult
		return nil
	case "google_search_result":
		googleSearchResultDelta := new(GoogleSearchResultDelta)
		if err := utils.UnmarshalJSON(data, &googleSearchResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_search_result) type GoogleSearchResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.GoogleSearchResultDelta = googleSearchResultDelta
		u.Type = StepDeltaDataTypeGoogleSearchResult
		return nil
	case "mcp_server_tool_result":
		mcpServerToolResultDelta := new(MCPServerToolResultDelta)
		if err := utils.UnmarshalJSON(data, &mcpServerToolResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mcp_server_tool_result) type MCPServerToolResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.MCPServerToolResultDelta = mcpServerToolResultDelta
		u.Type = StepDeltaDataTypeMcpServerToolResult
		return nil
	case "file_search_result":
		fileSearchResultDelta := new(FileSearchResultDelta)
		if err := utils.UnmarshalJSON(data, &fileSearchResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_search_result) type FileSearchResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.FileSearchResultDelta = fileSearchResultDelta
		u.Type = StepDeltaDataTypeFileSearchResult
		return nil
	case "google_maps_result":
		googleMapsResultDelta := new(GoogleMapsResultDelta)
		if err := utils.UnmarshalJSON(data, &googleMapsResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_maps_result) type GoogleMapsResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.GoogleMapsResultDelta = googleMapsResultDelta
		u.Type = StepDeltaDataTypeGoogleMapsResult
		return nil
	case "function_result":
		functionResultDelta := new(FunctionResultDelta)
		if err := utils.UnmarshalJSON(data, &functionResultDelta, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == function_result) type FunctionResultDelta within StepDeltaData: %w", string(data), err)
		}

		u.FunctionResultDelta = functionResultDelta
		u.Type = StepDeltaDataTypeFunctionResult
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StepDeltaDataTypeUnknown
		return nil
	}

}

func (u StepDeltaData) MarshalJSON() ([]byte, error) {
	if u.TextDelta != nil {
		return utils.MarshalJSON(u.TextDelta, "", true)
	}

	if u.ImageDelta != nil {
		return utils.MarshalJSON(u.ImageDelta, "", true)
	}

	if u.AudioDelta != nil {
		return utils.MarshalJSON(u.AudioDelta, "", true)
	}

	if u.DocumentDelta != nil {
		return utils.MarshalJSON(u.DocumentDelta, "", true)
	}

	if u.VideoDelta != nil {
		return utils.MarshalJSON(u.VideoDelta, "", true)
	}

	if u.ThoughtSummaryDelta != nil {
		return utils.MarshalJSON(u.ThoughtSummaryDelta, "", true)
	}

	if u.ThoughtSignatureDelta != nil {
		return utils.MarshalJSON(u.ThoughtSignatureDelta, "", true)
	}

	if u.TextAnnotationDelta != nil {
		return utils.MarshalJSON(u.TextAnnotationDelta, "", true)
	}

	if u.ArgumentsDelta != nil {
		return utils.MarshalJSON(u.ArgumentsDelta, "", true)
	}

	if u.CodeExecutionCallDelta != nil {
		return utils.MarshalJSON(u.CodeExecutionCallDelta, "", true)
	}

	if u.URLContextCallDelta != nil {
		return utils.MarshalJSON(u.URLContextCallDelta, "", true)
	}

	if u.GoogleSearchCallDelta != nil {
		return utils.MarshalJSON(u.GoogleSearchCallDelta, "", true)
	}

	if u.MCPServerToolCallDelta != nil {
		return utils.MarshalJSON(u.MCPServerToolCallDelta, "", true)
	}

	if u.FileSearchCallDelta != nil {
		return utils.MarshalJSON(u.FileSearchCallDelta, "", true)
	}

	if u.GoogleMapsCallDelta != nil {
		return utils.MarshalJSON(u.GoogleMapsCallDelta, "", true)
	}

	if u.CodeExecutionResultDelta != nil {
		return utils.MarshalJSON(u.CodeExecutionResultDelta, "", true)
	}

	if u.URLContextResultDelta != nil {
		return utils.MarshalJSON(u.URLContextResultDelta, "", true)
	}

	if u.GoogleSearchResultDelta != nil {
		return utils.MarshalJSON(u.GoogleSearchResultDelta, "", true)
	}

	if u.MCPServerToolResultDelta != nil {
		return utils.MarshalJSON(u.MCPServerToolResultDelta, "", true)
	}

	if u.FileSearchResultDelta != nil {
		return utils.MarshalJSON(u.FileSearchResultDelta, "", true)
	}

	if u.GoogleMapsResultDelta != nil {
		return utils.MarshalJSON(u.GoogleMapsResultDelta, "", true)
	}

	if u.FunctionResultDelta != nil {
		return utils.MarshalJSON(u.FunctionResultDelta, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type StepDeltaData: all fields are null")
}
