// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"
	"google.golang.org/genai/gaos/internal/utils"
)

type ToolType string

const (
	ToolTypeFunction      ToolType = "function"
	ToolTypeCodeExecution ToolType = "code_execution"
	ToolTypeURLContext    ToolType = "url_context"
	ToolTypeComputerUse   ToolType = "computer_use"
	ToolTypeMcpServer     ToolType = "mcp_server"
	ToolTypeGoogleSearch  ToolType = "google_search"
	ToolTypeFileSearch    ToolType = "file_search"
	ToolTypeGoogleMaps    ToolType = "google_maps"
	ToolTypeRetrieval     ToolType = "retrieval"
	ToolTypeUnknown       ToolType = "UNKNOWN"
)

// Tool - A tool that can be used by the model.
type Tool struct {
	Function      *Function       `queryParam:"inline" union:"member"`
	CodeExecution *CodeExecution  `queryParam:"inline" union:"member"`
	URLContext    *URLContext     `queryParam:"inline" union:"member"`
	ComputerUse   *ComputerUse    `queryParam:"inline" union:"member"`
	MCPServer     *MCPServer      `queryParam:"inline" union:"member"`
	GoogleSearch  *GoogleSearch   `queryParam:"inline" union:"member"`
	FileSearch    *FileSearch     `queryParam:"inline" union:"member"`
	GoogleMaps    *GoogleMaps     `queryParam:"inline" union:"member"`
	Retrieval     *Retrieval      `queryParam:"inline" union:"member"`
	UnknownRaw    json.RawMessage `json:"-" union:"unknown"`

	Type ToolType
}

func CreateToolFunction(function Function) Tool {
	typ := ToolTypeFunction

	return Tool{
		Function: &function,
		Type:     typ,
	}
}

func CreateToolCodeExecution(codeExecution CodeExecution) Tool {
	typ := ToolTypeCodeExecution

	return Tool{
		CodeExecution: &codeExecution,
		Type:          typ,
	}
}

func CreateToolURLContext(urlContext URLContext) Tool {
	typ := ToolTypeURLContext

	return Tool{
		URLContext: &urlContext,
		Type:       typ,
	}
}

func CreateToolComputerUse(computerUse ComputerUse) Tool {
	typ := ToolTypeComputerUse

	return Tool{
		ComputerUse: &computerUse,
		Type:        typ,
	}
}

func CreateToolMcpServer(mcpServer MCPServer) Tool {
	typ := ToolTypeMcpServer

	return Tool{
		MCPServer: &mcpServer,
		Type:      typ,
	}
}

func CreateToolGoogleSearch(googleSearch GoogleSearch) Tool {
	typ := ToolTypeGoogleSearch

	return Tool{
		GoogleSearch: &googleSearch,
		Type:         typ,
	}
}

func CreateToolFileSearch(fileSearch FileSearch) Tool {
	typ := ToolTypeFileSearch

	return Tool{
		FileSearch: &fileSearch,
		Type:       typ,
	}
}

func CreateToolGoogleMaps(googleMaps GoogleMaps) Tool {
	typ := ToolTypeGoogleMaps

	return Tool{
		GoogleMaps: &googleMaps,
		Type:       typ,
	}
}

func CreateToolRetrieval(retrieval Retrieval) Tool {
	typ := ToolTypeRetrieval

	return Tool{
		Retrieval: &retrieval,
		Type:      typ,
	}
}

func CreateToolUnknown(raw json.RawMessage) Tool {
	return Tool{
		UnknownRaw: raw,
		Type:       ToolTypeUnknown,
	}
}

func (u Tool) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Tool) IsUnknown() bool {
	return u.Type == ToolTypeUnknown
}

func (u *Tool) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolTypeUnknown
		return nil
	}

	switch dis.Type {
	case "function":
		function := new(Function)
		if err := utils.UnmarshalJSON(data, &function, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == function) type Function within Tool: %w", string(data), err)
		}

		u.Function = function
		u.Type = ToolTypeFunction
		return nil
	case "code_execution":
		codeExecution := new(CodeExecution)
		if err := utils.UnmarshalJSON(data, &codeExecution, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution) type CodeExecution within Tool: %w", string(data), err)
		}

		u.CodeExecution = codeExecution
		u.Type = ToolTypeCodeExecution
		return nil
	case "url_context":
		urlContext := new(URLContext)
		if err := utils.UnmarshalJSON(data, &urlContext, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == url_context) type URLContext within Tool: %w", string(data), err)
		}

		u.URLContext = urlContext
		u.Type = ToolTypeURLContext
		return nil
	case "computer_use":
		computerUse := new(ComputerUse)
		if err := utils.UnmarshalJSON(data, &computerUse, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == computer_use) type ComputerUse within Tool: %w", string(data), err)
		}

		u.ComputerUse = computerUse
		u.Type = ToolTypeComputerUse
		return nil
	case "mcp_server":
		mcpServer := new(MCPServer)
		if err := utils.UnmarshalJSON(data, &mcpServer, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mcp_server) type MCPServer within Tool: %w", string(data), err)
		}

		u.MCPServer = mcpServer
		u.Type = ToolTypeMcpServer
		return nil
	case "google_search":
		googleSearch := new(GoogleSearch)
		if err := utils.UnmarshalJSON(data, &googleSearch, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_search) type GoogleSearch within Tool: %w", string(data), err)
		}

		u.GoogleSearch = googleSearch
		u.Type = ToolTypeGoogleSearch
		return nil
	case "file_search":
		fileSearch := new(FileSearch)
		if err := utils.UnmarshalJSON(data, &fileSearch, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_search) type FileSearch within Tool: %w", string(data), err)
		}

		u.FileSearch = fileSearch
		u.Type = ToolTypeFileSearch
		return nil
	case "google_maps":
		googleMaps := new(GoogleMaps)
		if err := utils.UnmarshalJSON(data, &googleMaps, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_maps) type GoogleMaps within Tool: %w", string(data), err)
		}

		u.GoogleMaps = googleMaps
		u.Type = ToolTypeGoogleMaps
		return nil
	case "retrieval":
		retrieval := new(Retrieval)
		if err := utils.UnmarshalJSON(data, &retrieval, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == retrieval) type Retrieval within Tool: %w", string(data), err)
		}

		u.Retrieval = retrieval
		u.Type = ToolTypeRetrieval
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolTypeUnknown
		return nil
	}

}

func (u Tool) MarshalJSON() ([]byte, error) {
	if u.Function != nil {
		return utils.MarshalJSON(u.Function, "", true)
	}

	if u.CodeExecution != nil {
		return utils.MarshalJSON(u.CodeExecution, "", true)
	}

	if u.URLContext != nil {
		return utils.MarshalJSON(u.URLContext, "", true)
	}

	if u.ComputerUse != nil {
		return utils.MarshalJSON(u.ComputerUse, "", true)
	}

	if u.MCPServer != nil {
		return utils.MarshalJSON(u.MCPServer, "", true)
	}

	if u.GoogleSearch != nil {
		return utils.MarshalJSON(u.GoogleSearch, "", true)
	}

	if u.FileSearch != nil {
		return utils.MarshalJSON(u.FileSearch, "", true)
	}

	if u.GoogleMaps != nil {
		return utils.MarshalJSON(u.GoogleMaps, "", true)
	}

	if u.Retrieval != nil {
		return utils.MarshalJSON(u.Retrieval, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Tool: all fields are null")
}
