// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"google.golang.org/genai/gaos/internal/utils"
)

type TurnContentType string

const (
	TurnContentTypeArrayOfContent TurnContentType = "arrayOfContent"
	TurnContentTypeStr            TurnContentType = "str"
	TurnContentTypeUnknown        TurnContentType = "Unknown"
)

type TurnContent struct {
	ArrayOfContent []Content       `queryParam:"inline" union:"member"`
	Str            *string         `queryParam:"inline" union:"member"`
	UnknownRaw     json.RawMessage `json:"-" union:"unknown"`

	Type TurnContentType
}

func CreateTurnContentArrayOfContent(arrayOfContent []Content) TurnContent {
	typ := TurnContentTypeArrayOfContent

	return TurnContent{
		ArrayOfContent: arrayOfContent,
		Type:           typ,
	}
}

func CreateTurnContentStr(str string) TurnContent {
	typ := TurnContentTypeStr

	return TurnContent{
		Str:  &str,
		Type: typ,
	}
}

func CreateTurnContentUnknown(raw json.RawMessage) TurnContent {
	return TurnContent{
		UnknownRaw: raw,
		Type:       TurnContentTypeUnknown,
	}
}

func (u TurnContent) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u TurnContent) IsUnknown() bool {
	return u.Type == TurnContentTypeUnknown
}

func (u *TurnContent) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfContent []Content = []Content{}
	if err := utils.UnmarshalJSON(data, &arrayOfContent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TurnContentTypeArrayOfContent,
			Value: arrayOfContent,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TurnContentTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = TurnContentTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = TurnContentTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(TurnContentType)
	switch best.Type {
	case TurnContentTypeArrayOfContent:
		u.ArrayOfContent = best.Value.([]Content)
		return nil
	case TurnContentTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = TurnContentTypeUnknown
	return nil
}

func (u TurnContent) MarshalJSON() ([]byte, error) {
	if u.ArrayOfContent != nil {
		return utils.MarshalJSON(u.ArrayOfContent, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type TurnContent: all fields are null")
}

// Turn
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type Turn struct {
	// The originator of this turn. Must be user for input or model for
	// model output.
	Role    *string      `json:"role,omitzero"`
	Content *TurnContent `json:"content,omitzero"`
}

func (t Turn) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Turn) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Turn) GetRole() *string {
	if t == nil {
		return nil
	}
	return t.Role
}

func (t *Turn) GetContent() *TurnContent {
	if t == nil {
		return nil
	}
	return t.Content
}
