// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"google.golang.org/genai/gaos/internal/utils"
)

// Arguments - The arguments to pass to the URL context.
type Arguments struct {
	// The URLs to fetch.
	Urls []string `json:"urls,omitzero"`
}

func (a Arguments) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Arguments) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Arguments) GetUrls() []string {
	if a == nil {
		return nil
	}
	return a.Urls
}

// URLContextCallStep - URL context call step.
type URLContextCallStep struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"url_context_call" json:"type"`
	// Required. A unique ID for this specific tool call.
	ID string `json:"id"`
	// A signature hash for backend validation.
	Signature *string `json:"signature,omitzero"`
	// The arguments to pass to the URL context.
	Arguments Arguments `json:"arguments"`
}

func (u URLContextCallStep) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *URLContextCallStep) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *URLContextCallStep) GetType() string {
	return "url_context_call"
}

func (u *URLContextCallStep) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *URLContextCallStep) GetSignature() *string {
	if u == nil {
		return nil
	}
	return u.Signature
}

func (u *URLContextCallStep) GetArguments() Arguments {
	if u == nil {
		return Arguments{}
	}
	return u.Arguments
}
