// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"google.golang.org/genai/gaos/internal/utils"
)

// VideoContentMimeType - The mime type of the video.
type VideoContentMimeType string

const (
	VideoContentMimeTypeVideoMp4  VideoContentMimeType = "video/mp4"
	VideoContentMimeTypeVideoMpeg VideoContentMimeType = "video/mpeg"
	VideoContentMimeTypeVideoMpg  VideoContentMimeType = "video/mpg"
	VideoContentMimeTypeVideoMov  VideoContentMimeType = "video/mov"
	VideoContentMimeTypeVideoAvi  VideoContentMimeType = "video/avi"
	VideoContentMimeTypeVideoXFlv VideoContentMimeType = "video/x-flv"
	VideoContentMimeTypeVideoWebm VideoContentMimeType = "video/webm"
	VideoContentMimeTypeVideoWmv  VideoContentMimeType = "video/wmv"
	VideoContentMimeTypeVideo3gpp VideoContentMimeType = "video/3gpp"
)

func (e VideoContentMimeType) ToPointer() *VideoContentMimeType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VideoContentMimeType) IsExact() bool {
	if e != nil {
		switch *e {
		case "video/mp4", "video/mpeg", "video/mpg", "video/mov", "video/avi", "video/x-flv", "video/webm", "video/wmv", "video/3gpp":
			return true
		}
	}
	return false
}

// VideoContent - A video content block.
type VideoContent struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"video" json:"type"`
	// The video content.
	Data *string `json:"data,omitzero"`
	// The URI of the video.
	URI *string `json:"uri,omitzero"`
	// The mime type of the video.
	MimeType   *VideoContentMimeType `json:"mime_type,omitzero"`
	Resolution *MediaResolution      `json:"resolution,omitzero"`
}

func (v VideoContent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VideoContent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VideoContent) GetType() string {
	return "video"
}

func (v *VideoContent) GetData() *string {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *VideoContent) GetURI() *string {
	if v == nil {
		return nil
	}
	return v.URI
}

func (v *VideoContent) GetMimeType() *VideoContentMimeType {
	if v == nil {
		return nil
	}
	return v.MimeType
}

func (v *VideoContent) GetResolution() *MediaResolution {
	if v == nil {
		return nil
	}
	return v.Resolution
}
